In [ ]:
# H

# Tools

## Data preprocessing

Load a month of monthly Neighborhood Patterns, then prepare data for IPF.

In [27]:
%load_ext autoreload
%autoreload 2
import os
import random
import sqlite3 
import numpy as np
import json
import math

import pandas as pd

import Advan_operator as ad_op  

pd.set_option('display.max_columns', None)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Load monthly Neighborhood Patterns

#### Asign file locations

In [145]:
# data_dir = r'F:\SafeGraph\Advan_2023_API\Neighborhood_Patterns'   # Lenovo


data_dir = r'K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns'   # Dell 
save_dir = r'D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test'  # Dell

year = '2023'
month = 6

ACS_file = r"F:\Research\Wild_fire\cbg_acs_2019_county_tract_new20230929_cleaned.csv"
home_panel_fname = f"F:\SafeGraph\Advan_2023_API\Monthly_Patterns_home_panel_summary\Monthly_Patterns_home_panel_summary_2019_2023.csv"


month_dir = os.path.join(data_dir, str(year), f'{month:02}', '01')
no_dict_colum_fname = os.path.join(save_dir, f"NP_dict_column_{year}_{month:02}.csv")
device_home_areas_fname = os.path.join(save_dir, f"NP_split_device_home_areas_{year}_{month:02}.csv")
adjusted_dwelling_time_stop_CBG_fname     = os.path.join(save_dir, f"adjusted_dwelling_time_stop_CBG_{year}_{month:02}.csv")
adjusted_dwelling_time_stop_natinol_fname = os.path.join(save_dir, f"adjusted_dwelling_time_stop_natinol_{year}_{month:02}.csv")
person_per_device_fname = os.path.join(save_dir, f"person_per_device_{year}_{month:02}.csv")
restored_CBG_hourly_vistor_count_fname = os.path.join(save_dir, f"restored_hourly_vistor_count_CBG_{year}_{month:02}.csv")
restored_target_hourly_vistor_count_fname = os.path.join(save_dir, f"restored_hourly_vistor_count_target_{year}_{month:02}.csv")


# month_dir = r'K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01'
# CBG_list_fname = r"D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\ACS_2019_CBG_list.csv"

sqlite_fname = r'F:\Research\Wild_fire\Neighborhood_202306.db'


print("Month directory:", month_dir)
print("Save_dir directory:", save_dir)
print("ACS_file:", ACS_file)
print("home_panel file name:", home_panel_fname)

print("No dict colum file name:", no_dict_colum_fname)
print("Device home areas file name:", device_home_areas_fname)
print("Device person_per_device file name:", person_per_device_fname)


print("Device adjusted_dwelling_time_stop_CBG_fname:", adjusted_dwelling_time_stop_CBG_fname)
print("Device adjusted_dwelling_time_stop_natinol_fname:", adjusted_dwelling_time_stop_natinol_fname)

print("Restored_hourly_vistor_count_CBG file name:   ", restored_CBG_hourly_vistor_count_fname)
print("Restored_hourly_vistor_count_target file name:", restored_target_hourly_vistor_count_fname)

Month directory: K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01
Save_dir directory: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test
ACS_file: F:\Research\Wild_fire\cbg_acs_2019_county_tract_new20230929_cleaned.csv
home_panel file name: F:\SafeGraph\Advan_2023_API\Monthly_Patterns_home_panel_summary\Monthly_Patterns_home_panel_summary_2019_2023.csv
No dict colum file name: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\NP_dict_column_2023_06.csv
Device home areas file name: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\NP_split_device_home_areas_2023_06.csv
Device person_per_device file name: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\person_per_device_2023_06.csv
Device adjusted_dwelling_time_stop_CBG_fname: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\adjusted_dwelling_time_stop_CBG_2023_06.csv
Device adjusted_dwelling_time_stop_natinol_fname: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\adjusted_dwelling_time_stop_natinol_2023_06.csv
Restored_hourly_vistor_count_CBG file name:    D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\restored_hourly_vistor_count_CBG_2023_06.csv
Restored_hourly_vistor_count_target file name: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\restored_hourly_vistor_count_target_2023_06.csv

In [10]:
# Load monthly neighborhood patterns

month_df = ad_op.load_neighborhood_monthly_folder(folder=month_dir, extions=['gz'], verbose=True)
month_df

Found target files: 22
The top 5 and bottom 5 files:
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\data_01af1467-0604-be6e-0043-0b8700e85436_53_1_0.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\data_01af1467-0604-be6e-0043-0b8700e85436_53_1_1.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\data_01af1467-0604-be6e-0043-0b8700e85436_53_1_10.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\data_01af1467-0604-be6e-0043-0b8700e85436_53_1_2.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\data_01af1467-0604-be6e-0043-0b8700e85436_53_1_3.csv.gz
...
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-658-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-659-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-660-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-661-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-662-DATE_RANGE_START-2023-06-01.csv.gz
Found 11 Neighborhood_Patterns_US files:

K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-652-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-653-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-654-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-655-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-656-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-657-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-658-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-659-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-660-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-661-DATE_RANGE_START-2023-06-01.csv.gz
K:\SafeGraph\Advan_2023_API\Neighborhood_Patterns\2023\06\01\Neighborhood_Patterns_US-662-DATE_RANGE_START-2023-06-01.csv.gz
Loading files...

,AREA,AREA_TYPE,ORIGIN_AREA_TYPE,DATE_RANGE_START,DATE_RANGE_END,DAY_COUNTS,RAW_STOP_COUNTS,RAW_DEVICE_COUNTS,STOPS_BY_DAY,STOPS_BY_EACH_HOUR,DEVICE_HOME_AREAS,WEEKDAY_DEVICE_HOME_AREAS,WEEKEND_DEVICE_HOME_AREAS,BREAKFAST_DEVICE_HOME_AREAS,LUNCH_DEVICE_HOME_AREAS,DINNER_DEVICE_HOME_AREAS,NIGHTLIFE_DEVICE_HOME_AREAS,WORK_HOURS_DEVICE_HOME_AREAS,WORK_BEHAVIOR_DEVICE_HOME_AREAS,DEVICE_DAYTIME_AREAS,DISTANCE_FROM_HOME,DISTANCE_FROM_PRIMARY_DAYTIME_LOCATION,MEDIAN_DWELL,TOP_SAME_DAY_BRAND,TOP_SAME_MONTH_BRAND,POPULARITY_BY_EACH_HOUR,POPULARITY_BY_HOUR_MONDAY,POPULARITY_BY_HOUR_TUESDAY,POPULARITY_BY_HOUR_WEDNESDAY,POPULARITY_BY_HOUR_THURSDAY,POPULARITY_BY_HOUR_FRIDAY,POPULARITY_BY_HOUR_SATURDAY,POPULARITY_BY_HOUR_SUNDAY,DEVICE_TYPE,ISO_COUNTRY_CODE,REGION,Y,M
0,470370112006,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",6558,4181,"[208,162,223,224,92,215,261,174,260,218,326,15...","[0,0,0,0,0,0,0,0,22,22,39,6,14,26,28,0,7,10,5,...","{""470370112006"":148,""470370153004"":47,""4703701...","{""470370112006"":103,""470370153004"":34,""4703701...","{""470370112006"":15,""470370110022"":4,""470370116...","{""470370112006"":7,""470370110022"":4,""4703701160...","{""470370112006"":15,""470370153004"":4,""470370110...","{""470370112006"":31,""470370153004"":8,""470370110...","{""470370153004"":4,""470370110022"":4,""4703701950...","{""470370112006"":20,""470370153004"":10,""47037011...","{""470370193001"":4,""470370119002"":4,""4703701562...","{""470370112006"":95,""470370195004"":53,""47037019...",3940.0,6356.0,32.066667,"{""Mall"":15,""Dollar Tree"":7,""Kroger"":7,""Walmart...","{""Mall"":64,""Walmart"":40,""Kroger"":39,""Gas Stati...","[9,17,18,21,20,7,7,10,33,44,46,44,50,69,45,9,1...","[137,143,151,147,146,151,142,180,135,189,172,2...","[126,146,150,122,122,151,157,176,245,191,164,2...","[127,141,147,146,152,151,124,175,165,191,211,2...","[126,141,133,139,162,153,142,149,182,242,321,3...","[159,131,131,139,133,148,129,166,161,119,132,1...","[70,83,89,89,77,91,98,116,118,155,93,74,127,17...","[131,127,148,157,156,173,193,214,190,240,300,2...","{""android"":1630,""ios"":1323}",US,TN,2023,6
1,310199694003,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",42090,8019,"[1842,1829,1559,1210,1200,1150,1338,1712,1755,...","[0,10,17,23,51,16,89,56,90,133,116,174,183,106...","{""310199694003"":560,""310199692031"":242,""310199...","{""310199694003"":469,""310199692031"":195,""310199...","{""310199694003"":128,""310199692031"":31,""3101996...","{""310199694003"":104,""310199692031"":27,""3101996...","{""310199694003"":141,""310199692031"":93,""3101996...","{""310199694003"":143,""310199692031"":51,""3101996...","{""310199694003"":6,""310199692031"":4,""3101996920...","{""310199694003"":247,""310199692031"":145,""310199...","{""310199694003"":5,""310199690001"":8,""3101996920...","{""310199694003"":665,""310199692031"":248,""310199...",1988.0,1287.0,10.483333,"{""Hospitals"":22,""Walmart"":21,""Mall"":20,""Gas St...","{""Walmart"":54,""Mall"":53,""Gas Stations"":41,""Hos...","[110,114,124,133,164,167,225,236,230,239,263,3...","[324,345,348,362,356,478,574,739,683,817,824,8...","[334,378,362,398,425,483,582,691,833,869,881,9...","[449,470,423,465,494,593,664,783,797,775,715,8...","[423,477,462,474,503,589,837,964,1068,1007,112...","[485,512,505,516,619,712,896,1085,1245,1110,12...","[391,430,384,427,416,512,487,515,565,624,613,6...","[443,433,415,465,485,512,511,516,594,635,685,6...","{""android"":2740,""ios"":2349}",US,NE,2023,6
2,550939606003,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",33042,4781,"[1594,1195,789,1047,930,927,726,928,1295,1130,...","[0,0,5,42,74,42,23,59,82,145,70,72,81,71,64,11...","{""550939606003"":305,""550939606001"":85,""2704908...","{""550939606003"":197,""550939606001"":54,""2704908...","{""550939606003"":130,""550939606001"":15,""2704908...","{""550939606003"":46,""550939606001"":5,""270490801...","{""550939606003"":70,""550939606001"":22,""27049080...","{""550939606003"":97,""550939606001"":20,""27049080...","{""550939606003"":7,""270490801025"":4,""2704908020...","{""550939606003"":92,""550939606001"":30,""27049080...","{""550939606003"":4,""550939606001"":6,""2704908020...","{""550939606003"":212,""550939607001"":66,""5509396...",5057.0,8137.0,11.366667,"{""Gas Stations"":9,""Kwik Trip"":9,""Walmart"":9,""M...","{""Walmart"":39,""Mall"":37,""Gas Stations"":33,""Kwi...","[83,88,94,135,163,155,129,119,130,181,136,179,...","[452,502,504,557,525,455,475,474,458,482,496,5...","[505,534,510,524,547,473,529,606,553,590,498,5...","[392,449,441,466,485,424,445,419,498,508,484,5...","[530,575,582,639,705,683,702,619,643,743,669,7...","[700,727,755,715,727,761,788,815,846,908,777,7...","[442,446,510,578,630,663,750,756,728,670,638,7...","[550,597,612,640,647,700,794,885,870,800,730,6...","{""android"":2400,""ios"":1295}",US,WI,2023,6
3,450770112042,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",11249,3083,"[280,354,256,461,475,677,451,321,401,479,187,2...","[42,0,0,0,0,0,10,28,16,0,17,14,8,36,11,14,0,51...","{""450770112042"":113,""450730306021"":65,""4507701...","{""450770112042"":93,""450730306021"":53,""45077011...","{""450770112042"":33,""450730306021"":4,""450770112...","{""450770112042"":15,""450730306021"":4,""450770112...","{""450770112042"":22,""450730306021"":9,""450770112...","{""450770112042"":32,""450730306021"":13,""45077011...","{""450770112042"":4,""450730306021"":6,""4507701120...","{""450770112042"":34,""450730306021"":21,""45077011...","{""450770112042"":5,""450770112041"":4,""4507701120...","{""450770112042"":111,""450770111011"":77,""4507701...",6620.0,5274.0,22.566667,"{""Mall"":21,""Walmart"":14,""Universities and Coll...","{""Mall"":67,""Walmart"":56,""Gas Stations"":32,""Ing...","[36,25,27,28,22,28,39,72,22,12,14,16,10,55,37,...","[248,255,255,242,270,294,316,320,239,260,270,2...","[213,269,303,316,330,333,362,431,335,342,341,2...","[226,249,255,269,273,310,361,448,450,429,408,3...","[259,231,243,213,242,286,384,424,462,351,335,3...","[203,230,228,248,243,276,300,455,430,354,333,3...","[184,259,247,247,259,253,294,320,354,362,394,4...","[181,212,240,241,249,245,240,254,229,233,272,2...","{""android"":886,""ios"":997}",US,SC,2023,6
4,60375545222,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",14560,6277,"[313,430,408,450,351,886,451,358,432,808,613,2...","[0,0,0,0,0,14,0,0,0,24,0,36,22,22,0,17,37,0,96...","{""060375545222"":28,""060375545122"":12,""32003006...","{""060375545222"":16,""060375545122"":6,""320030067...","{""060375545222"":4,""060375545212"":9,""0603755452...","{""060375545222"":4,""060375545212"":6,""0603755480...","{""060375545222"":5,""060375700012"":4,""0605911011...","{""060375545222"":4,""060375545122"":12,""320030067...","{""060375545212"":4,""060375545223"":4,""0603755360...","{""060375545222"":5,""060375545122"":4,""0603757000...","{""060375545212"":4,""060375541052"":4,""0603755490...","{""060375545222"":29,""060375545223"":14,""06037554...",9763.0,8771.0,25.483333,"{""Mall"":25,""Macerich"":18,""Starbucks"":10,""Amazo...","{""Mall"":86,""Macerich"":45,""Starbucks"":43,""Walma...","[0,0,0,0,0,20,0,0,0,23,23,59,81,121,97,77,76,5...","[102,101,119,100,93,103,102,116,77,213,396,353...","[123,97,121,117,135,160,121,96,79,258,339,358,...","[74,77,82,73,77,76,122,60,135,139,133,259,409,...","[76,73,78,77,81,102,76,102,132,199,254,213,272...","[60,60,62,57,54,95,117,113,154,220,254,549,533...","[94,116,99,80,102,118,137,123,78,192,295,352,3...","[62,54,60,83,81,94,93,135,133,212,376,388,333,...","{""android"":3534,""ios"":2013}",US,CA,2023,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20952,60375433211,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",76304,13849,"[2619,2600,2303,1380,3382,2773,2634,2639,2966,...","[0,39,38,24,0,43,60,329,241,138,211,172,158,21...","{""060375433211"":81,""060375433051"":21,""06037543...","{""060375433211"":59,""060375433051"":15,""06037543...","{""060375433211"":10,""060375433212"":4,""060375433...","{""060375433211"":12,""060375433051"":4,""060375433...","{""060375433211"":17,""060375433051"":4,""060375433...","{""060375433211"":16,""060375433212"":4,""060375430...","{""060375433211"":4,""060375433051"":4,""0603754332...","{""060375433211"":31,""060375433051"":10,""06037543...","{""060375433211"":4,""060379800281"":4,""0603760300...","{""060375433211"":142,""060375433051"":34,""0603754...",9998.0,5854.0,55.333333,"{""Universities and Colleges"":24,""Mall"":22,""AEG...","{""Mall"":76,""Walmart"":40,""Universities and Coll...","[162,197,235,240,196,214,221,330,447,467,495,3...","[533,570,604,593,611,805,887,966,1222,1295,149...","[748,703,532,490,490,567,827,1057,1414,1551,16...","[629,664,607,594,568,787,946,1237,1608,1589,16...","[925,988,919,868,725,903,1004,1261,1629,1652,1...","[803,863,789,726,825,1046,1195,1414,1707,1805,...","[570,708,649,667,731,769,822,850,863,900,843,8...","[605,612,571,572,547,571,570,604,730,851,848,7...","{""android"":9581,""ios"":3204}",US,CA,2023,6
20953,390375701021,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",12605,1413,"[241,129,294,223,215,303,204,457,451,513,344,3...","[0,0,0,0,0,0,0,0,15,26,9,0,7,13,39,6,14,0,23,1...","{""390375701021"":183,""390375701023"":39,""3903754...","{""390375701021"":121,""390375701023"":23,""3903754...","{""390375701021"":73,""390375701023"":4,""390375401...","{""390375701021"":32,""390375701023"":4,""390375401...","{""390375701021"":32,""390375701023"":5,""390375401...","{""390375701021"":65,""390375701023"":6,""390375401...","{""390375701021"":9,""390375701023"":18,""390375701...","{""390375701021"":64,""390375701023"":10,""39037540...","{""390375701021"":13,""390375701023"":7,""390375701...","{""390375701021"":133,""390375701023"":30,""3903757...",1672.0,1672.0,20.883333,"{""Golf Courses"":32,""Mall"":16,""Walmart"":11,""Kro...","{""Mall"":41,""Golf Courses"":40,""Walmart"":38,""Kro...","[91,95,86,90,81,77,70,61,56,69,55,43,45,57,65,...","[276,272,250,240,174,206,259,291,280,321,284,2...","[283,270,268,261,242,265,287,296,321,332,303,3...","[330,344,343,340,297,309,268,278,236,247,246,2...","[425,418,421,418,353,382,383,357,396,420,413,3...","[364,372,369,372,329,327,378,315,318,330,347,3...","[277,291,284,280,283,303,345,329,321,315,292,3...","[307,353,322,335,300,316,329,349,368,396,428,4...","{""android"":617,""ios"":378}",US,OH,2023,6
20954,201259509002,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",26633,4948,"[958,1126,1618,804,807,995,980,1092,1460,705,5...","[5,0,0,0,8,8,39,50,85,55,36,28,59,132,41,82,61...","{""201259509002"":151,""201259508001"":93,""2009995...","{""201259509002"":105,""201259508001"":58,""2009995...","{""201259509002"":61,""201259508001"":26,""20099950...","{""201259509002"":23,""201259508001"":9,""200999506...","{""201259509002"":46,""201259508001"":27,""20099950...","{""201259509002"":45,""201259508001"":16,""20099950...","{""201259509002"":4,""201259508001"":14,""401051721...","{""201259509002"":51,""201259508001"":37,""20099950...","{""200999506001"":4,""201259510002"":4,""2012595070...","{""201259509002"":170,""201259510003"":106,""201259...",7476.0,5267.0,20.033333,"{""Walmart"":52,""Gas Stations"":11,""CVR Partners""...","{""Walmart"":75,""Mall"":46,""Gas Stations"":41,""Hos...","[28,39,47,35,54,54,67,87,107,119,87,86,108,204...","[190,192,196,192,214,204,236,338,267,344,336,3...","[154,161,156,178,197,212,263,331,386,476,484,4...","[191,188,177,216,286,254,250,343,380,460,537,5...","[284,315,327,314,354,332,402,495,505,675,639,6...","[306,325,334,336,339,337,353,410,579,616,714,6...","[254,214,249,265,303,302,342,350,395,430,471,5...","[176,203,200,228,223,252,260,311,345,384,375,3...","{""android"":2675,""ios"":1362}",US,KS,2023,6
20955,550790190003,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",4628,1532,"[142,92,79,77,133,149,173,175,280,127,78,132,1...","[15,0,0,0,0,0,0,0,0,10,0,14,0,0,8,8,17,0,25,31...","{""550790190003"":26,""550790190005"":13,""55079019...","{""550790190003"":17,""550790190005"":9,""550790190...","{""550790190003"":6,""550790190005"":4,""5507901900...","{""550790190003"":4,""550790190005"":4,""5507901900...","{""550790190003"":4,""550790190005"":4,""5507901900...","{""550790190003"":4,""550790190005"":4,""5507901900...","{""550790190001"":4,""550790191002"":4,""5507901910...","{""550790190003"":5,""550790190005"":6,""5507901900...","{""550790190005"":4,""550790190004"":7,""5507918740...","{""550790190003"":14,""550790190001"":8,""550790190...",2130.0,2131.0,40.950000,"{""Mall"":24,""Hospitals"":10,""Pick 'n Save"":8,""Wa...","{""Mall"":56,""Walmart"":50,""Pick 'n Save"":36,""Gas...","[39,42,38,39,41,41,41,42,38,61,41,37,25,24,34,...","[115,133,134,130,147,142,155,162,181,165,158,1...","[68,117,147,127,134,116,130,160,161,165,182,15...","[107,134,157,140,127,128,135,120,166,196,166,1...","[188,201,156,147,126,133,157,162,147,199,195,1...","[174,199,179,142,143,165,188,200,206,196,187,1...","[83,100,114,103,101,103,93,105,145,126,133,188...","[109,140,171,149,130,136,147,146,142,87,65,92,...","{""android"":820,""ios"":369}",US,WI,2023,6
20956,540879631003,Census Block Group,Census Block Group,2023-06-01 00:00:00.000,2023-07-01 00:00:00.000,"{""Monday"":4,""Tuesday"":4,""Wednesday"":4,""Thursda...",5960,931,"[64,144,188,154,112,162,168,199,141,171,69,143...","[11,0,0,0,0,0,0,0,13,23,0,0,0,17,0,0,0,0,9,0,0...","{""540879631003"":45,""540390111003"":12,""42133021...","{""540879631003"":28,""540390111003"":8,""421330217...","{""540879631003"":11,""540390111003"":7,""540159579...","{""540879631003"":6,""540390111003"":4,""5401595790...","{""540879631003"":9,""540390111003"":4,""5401595790...","{""540879631003"":18,""540390111003"":5,""421330217...","{""540879631003"":4,""540679502001"":4,""5403901130...","{""540879631003"":18,""540390111003"":4,""421330217...","{""540879631003"":4,""540159579002"":5,""5406795020...","{""540879631003"":45,""540390111003"":16,""54015958...",22199.0,18099.0,10.033333,"{""Mall"":13,""ExxonMobil"":11,""Walmart"":8,""McDona...","{""Mall"":51,""Walmart"":46,""Gas Stations"":32,""Exx...","[18,24,32,26,14,18,24,15,26,47,38,32,27,30,24,...","[70,119,105,93,100,93,104,90,109,100,121,140,1...","[61,94,97,115,96,111,132,118,147,140,142,149,1...","[102,103,102,104,106,100,114,120,120,153,185,2...","[131,150,173,167,154,157,157,170,189,198,199,1...","[128,145,149,147,157,166,155,168,176,170,195,1...","[120,133,137,151,141,148,152,161,175,211,185,2...","[130,137,163,160,157,143,132,144,137,139,99,92...","{""android"":398,""ios"":389}",US,WV,2023,6

### Save the a single CSV for further use, only keep the non-dictionary columns.

In [33]:
non_dict_columns = ['AREA', 
                    "STOPS_BY_DAY", 
                    "RAW_STOP_COUNTS", 
                    "RAW_DEVICE_COUNTS", 
                    "MEDIAN_DWELL", 
                    "STOPS_BY_EACH_HOUR"]
# save CSV file
# month_df[non_dict_columns].to_csv(no_dict_colum_fname, index=False)
# print("Combined CSV wihouth dictionary columns was saved at:", no_dict_colum_fname)

In [162]:
### Split the DEVICE_HOME_AREAS column

In [61]:
month_df = month_df.sort_values("AREA")
device_home_areas_df = ad_op.split_a_dictionary_column(np_df=month_df.iloc[:], dest_col='AREA', origin_col='DEVICE_HOME_AREAS', value_name='device')
print("Sorting...")
# device_home_areas_df = device_home_areas_df.sort_values(['origin', 'destination'])
# device_home_areas_df = device_home_areas_df.sort_values(['origin', 'device'])
device_home_areas_df['origin'] = device_home_areas_df['origin'].astype(str).str.zfill(12)
device_home_areas_df['destination'] = device_home_areas_df['destination'].astype(str).str.zfill(12)
device_home_areas_df['device'] = device_home_areas_df['device'].astype(int)

print("Saving...")
device_home_areas_df.to_csv(device_home_areas_fname, index=False)
device_home_areas_df

Sorting...
Saving...

                origin   destination  device
0         010010201001  010010201001      84
1         010010208021  010010201001      63
2         010510313001  010010201001      53
3         010010205001  010010201001      42
4         011010059011  010010201001      32
...                ...           ...     ...
99501279  370810105002  780309900000       4
99501280  530330284024  780309900000       4
99501281  780309601002  780309900000       4
99501282  120860090361  780309900000       4
99501283  483396920021  780309900000       4

[99501284 rows x 3 columns]

###	Adjust stop count by dwelling time

Load the raw stop data and Neighorhood Patterns table.

In [3]:
# Load the raw stop data and Neighorhood Patterns table.

# device_home_areas_df = pd.read_csv(device_home_areas_fname)
print("Loading no_dict_colum CSV file:", no_dict_colum_fname)
no_dict_colum_df = pd.read_csv(no_dict_colum_fname)

no_dict_colum_df

,AREA,STOPS_BY_DAY,RAW_STOP_COUNTS,RAW_DEVICE_COUNTS,MEDIAN_DWELL,STOPS_BY_EACH_HOUR
0,470370112006,"[208,162,223,224,92,215,261,174,260,218,326,15...",6558,4181,32.066667,"[0,0,0,0,0,0,0,0,22,22,39,6,14,26,28,0,7,10,5,..."
1,310199694003,"[1842,1829,1559,1210,1200,1150,1338,1712,1755,...",42090,8019,10.483333,"[0,10,17,23,51,16,89,56,90,133,116,174,183,106..."
2,550939606003,"[1594,1195,789,1047,930,927,726,928,1295,1130,...",33042,4781,11.366667,"[0,0,5,42,74,42,23,59,82,145,70,72,81,71,64,11..."
3,450770112042,"[280,354,256,461,475,677,451,321,401,479,187,2...",11249,3083,22.566667,"[42,0,0,0,0,0,10,28,16,0,17,14,8,36,11,14,0,51..."
4,60375545222,"[313,430,408,450,351,886,451,358,432,808,613,2...",14560,6277,25.483333,"[0,0,0,0,0,14,0,0,0,24,0,36,22,22,0,17,37,0,96..."
...,...,...,...,...,...,...
220679,60375433211,"[2619,2600,2303,1380,3382,2773,2634,2639,2966,...",76304,13849,55.333333,"[0,39,38,24,0,43,60,329,241,138,211,172,158,21..."
220680,390375701021,"[241,129,294,223,215,303,204,457,451,513,344,3...",12605,1413,20.883333,"[0,0,0,0,0,0,0,0,15,26,9,0,7,13,39,6,14,0,23,1..."
220681,201259509002,"[958,1126,1618,804,807,995,980,1092,1460,705,5...",26633,4948,20.033333,"[5,0,0,0,8,8,39,50,85,55,36,28,59,132,41,82,61..."
220682,550790190003,"[142,92,79,77,133,149,173,175,280,127,78,132,1...",4628,1532,40.950000,"[15,0,0,0,0,0,0,0,0,10,0,14,0,0,8,8,17,0,25,31..."
220683,540879631003,"[64,144,188,154,112,162,168,199,141,171,69,143...",5960,931,10.033333,"[11,0,0,0,0,0,0,0,13,23,0,0,0,17,0,0,0,0,9,0,0..."

In [4]:
non_adjusted_dwell_time_stop_CBG_arr = ad_op.adjust_stop_by_dwelling_time(np_df=no_dict_colum_df.iloc[:], adjust_dwell_time=False, clean_negative=True)
print("sum of non_adjusted_dwell_time_stop_CBG_arr (million):", non_adjusted_dwell_time_stop_CBG_arr.sum().sum()/1000000)
print("shape of non_adjusted_dwell_time_stop_CBG_arr:", non_adjusted_dwell_time_stop_CBG_arr.shape)

sum of non_adjusted_dwell_time_stop_CBG_arr (million): 4099.559846
shape of non_adjusted_dwell_time_stop_CBG_arr: (220684, 720)

In [5]:
adjusted_dwell_time_stop_CBG_arr = ad_op.adjust_stop_by_dwelling_time(np_df=no_dict_colum_df.iloc[:], adjust_dwell_time=True, clean_negative=True)

adjusted_dwell_time_stop_national_arr = adjusted_dwell_time_stop_CBG_arr.sum(axis=0)

print("sum of adjusted_dwell_time_stop_CBG_arr (million):", adjusted_dwell_time_stop_CBG_arr.sum().sum()/1000000)
print("sum of adjusted_dwell_time_stop_national_arr (million):", adjusted_dwell_time_stop_national_arr.sum().sum()/1000000)
print("shape of adjusted_dwell_time_stop_CBG_arr:", adjusted_dwell_time_stop_CBG_arr.shape)

sum of adjusted_dwell_time_stop_CBG_arr (million): 5196.196864
sum of adjusted_dwell_time_stop_national_arr (million): 5196.196864
shape of adjusted_dwell_time_stop_CBG_arr: (220684, 720)

In [64]:
# hourly_columns
# adjusted_dwell_time_stop_national_arr.shape

(720,)

Convert numpy array to DataFrame

In [11]:
# convert numpy array to DataFrame
# CBG level
hourly_columns = [f'hour_{h+1}' for h in range(adjusted_dwell_time_stop_CBG_arr.shape[1])]
adjusted_dwelling_time_stop_CBG_df = pd.DataFrame(adjusted_dwell_time_stop_CBG_arr, columns=hourly_columns)
adjusted_dwelling_time_stop_CBG_df['CBG'] = no_dict_colum_df['AREA'].astype(str).str.zfill(12).to_list()
adjusted_dwelling_time_stop_CBG_df = adjusted_dwelling_time_stop_CBG_df[['CBG'] + hourly_columns]  # reorder columns
adjusted_dwelling_time_stop_CBG_df = adjusted_dwelling_time_stop_CBG_df.sort_values('CBG')


# national level
adjusted_dwelling_time_stop_natinol_df = pd.DataFrame(adjusted_dwell_time_stop_national_arr, columns=['stop'])

adjusted_dwelling_time_stop_CBG_df

,CBG,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,hour_9,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,hour_24,hour_25,hour_26,hour_27,hour_28,hour_29,hour_30,hour_31,hour_32,hour_33,hour_34,hour_35,hour_36,hour_37,hour_38,hour_39,hour_40,hour_41,hour_42,hour_43,hour_44,hour_45,hour_46,hour_47,hour_48,hour_49,hour_50,hour_51,hour_52,hour_53,hour_54,hour_55,hour_56,hour_57,hour_58,hour_59,hour_60,hour_61,hour_62,hour_63,hour_64,hour_65,hour_66,hour_67,hour_68,hour_69,hour_70,hour_71,hour_72,hour_73,hour_74,hour_75,hour_76,hour_77,hour_78,hour_79,hour_80,hour_81,hour_82,hour_83,hour_84,hour_85,hour_86,hour_87,hour_88,hour_89,hour_90,hour_91,hour_92,hour_93,hour_94,hour_95,hour_96,hour_97,hour_98,hour_99,hour_100,hour_101,hour_102,hour_103,hour_104,hour_105,hour_106,hour_107,hour_108,hour_109,hour_110,hour_111,hour_112,hour_113,hour_114,hour_115,hour_116,hour_117,hour_118,hour_119,hour_120,hour_121,hour_122,hour_123,hour_124,hour_125,hour_126,hour_127,hour_128,hour_129,hour_130,hour_131,hour_132,hour_133,hour_134,hour_135,hour_136,hour_137,hour_138,hour_139,hour_140,hour_141,hour_142,hour_143,hour_144,hour_145,hour_146,hour_147,hour_148,hour_149,hour_150,hour_151,hour_152,hour_153,hour_154,hour_155,hour_156,hour_157,hour_158,hour_159,hour_160,hour_161,hour_162,hour_163,hour_164,hour_165,hour_166,hour_167,hour_168,hour_169,hour_170,hour_171,hour_172,hour_173,hour_174,hour_175,hour_176,hour_177,hour_178,hour_179,hour_180,hour_181,hour_182,hour_183,hour_184,hour_185,hour_186,hour_187,hour_188,hour_189,hour_190,hour_191,hour_192,hour_193,hour_194,hour_195,hour_196,hour_197,hour_198,hour_199,hour_200,hour_201,hour_202,hour_203,hour_204,hour_205,hour_206,hour_207,hour_208,hour_209,hour_210,hour_211,hour_212,hour_213,hour_214,hour_215,hour_216,hour_217,hour_218,hour_219,hour_220,hour_221,hour_222,hour_223,hour_224,hour_225,hour_226,hour_227,hour_228,hour_229,hour_230,hour_231,hour_232,hour_233,hour_234,hour_235,hour_236,hour_237,hour_238,hour_239,hour_240,hour_241,hour_242,hour_243,hour_244,hour_245,hour_246,hour_247,hour_248,hour_249,hour_250,hour_251,hour_252,hour_253,hour_254,hour_255,hour_256,hour_257,hour_258,hour_259,hour_260,hour_261,hour_262,hour_263,hour_264,hour_265,hour_266,hour_267,hour_268,hour_269,hour_270,hour_271,hour_272,hour_273,hour_274,hour_275,hour_276,hour_277,hour_278,hour_279,hour_280,hour_281,hour_282,hour_283,hour_284,hour_285,hour_286,hour_287,hour_288,hour_289,hour_290,hour_291,hour_292,hour_293,hour_294,hour_295,hour_296,hour_297,hour_298,hour_299,hour_300,hour_301,hour_302,hour_303,hour_304,hour_305,hour_306,hour_307,hour_308,hour_309,hour_310,hour_311,hour_312,hour_313,hour_314,hour_315,hour_316,hour_317,hour_318,hour_319,hour_320,hour_321,hour_322,hour_323,hour_324,hour_325,hour_326,hour_327,hour_328,hour_329,hour_330,hour_331,hour_332,hour_333,hour_334,hour_335,hour_336,hour_337,hour_338,hour_339,hour_340,hour_341,hour_342,hour_343,hour_344,hour_345,hour_346,hour_347,hour_348,hour_349,hour_350,hour_351,hour_352,hour_353,hour_354,hour_355,hour_356,hour_357,hour_358,hour_359,hour_360,hour_361,hour_362,hour_363,hour_364,hour_365,hour_366,hour_367,hour_368,hour_369,hour_370,hour_371,hour_372,hour_373,hour_374,hour_375,hour_376,hour_377,hour_378,hour_379,hour_380,hour_381,hour_382,hour_383,hour_384,hour_385,hour_386,hour_387,hour_388,hour_389,hour_390,hour_391,hour_392,hour_393,hour_394,hour_395,hour_396,hour_397,hour_398,hour_399,hour_400,hour_401,hour_402,hour_403,hour_404,hour_405,hour_406,hour_407,hour_408,hour_409,hour_410,hour_411,hour_412,hour_413,hour_414,hour_415,hour_416,hour_417,hour_418,hour_419,hour_420,hour_421,hour_422,hour_423,hour_424,hour_425,hour_426,hour_427,hour_428,hour_429,hour_430,hour_431,hour_432,hour_433,hour_434,hour_435,hour_436,hour_437,hour_438,hour_439,hour_440,hour_441,hour_442,hour_443,hour_444,hour_445,hour_446,hour_447,hour_448,hour_449,hour_450,hour_451,hour_452,hour_453,hour_454,hour_455,hour_456,hour_457,hour_458,hour_459,hour_460,hour_461,hour_462,hour_463,hour_464,hour_465,hour_466,hour_467,hour_468,hour_469,hour_470,hour_471,hour_472,hour_473,hour_474,hour_475,hour_476,hour_477,hour_478,hour_479,hour_480,hour_481,hour_482,hour_483,hour_484,hour_485,hour_486,hour_487,hour_488,hour_489,hour_490,hour_491,hour_492,hour_493,hour_494,hour_495,hour_496,hour_497,hour_498,hour_499,hour_500,hour_501,hour_502,hour_503,hour_504,hour_505,hour_506,hour_507,hour_508,hour_509,hour_510,hour_511,hour_512,hour_513,hour_514,hour_515,hour_516,hour_517,hour_518,hour_519,hour_520,hour_521,hour_522,hour_523,hour_524,hour_525,hour_526,hour_527,hour_528,hour_529,hour_530,hour_531,hour_532,hour_533,hour_534,hour_535,hour_536,hour_537,hour_538,hour_539,hour_540,hour_541,hour_542,hour_543,hour_544,hour_545,hour_546,hour_547,hour_548,hour_549,hour_550,hour_551,hour_552,hour_553,hour_554,hour_555,hour_556,hour_557,hour_558,hour_559,hour_560,hour_561,hour_562,hour_563,hour_564,hour_565,hour_566,hour_567,hour_568,hour_569,hour_570,hour_571,hour_572,hour_573,hour_574,hour_575,hour_576,hour_577,hour_578,hour_579,hour_580,hour_581,hour_582,hour_583,hour_584,hour_585,hour_586,hour_587,hour_588,hour_589,hour_590,hour_591,hour_592,hour_593,hour_594,hour_595,hour_596,hour_597,hour_598,hour_599,hour_600,hour_601,hour_602,hour_603,hour_604,hour_605,hour_606,hour_607,hour_608,hour_609,hour_610,hour_611,hour_612,hour_613,hour_614,hour_615,hour_616,hour_617,hour_618,hour_619,hour_620,hour_621,hour_622,hour_623,hour_624,hour_625,hour_626,hour_627,hour_628,hour_629,hour_630,hour_631,hour_632,hour_633,hour_634,hour_635,hour_636,hour_637,hour_638,hour_639,hour_640,hour_641,hour_642,hour_643,hour_644,hour_645,hour_646,hour_647,hour_648,hour_649,hour_650,hour_651,hour_652,hour_653,hour_654,hour_655,hour_656,hour_657,hour_658,hour_659,hour_660,hour_661,hour_662,hour_663,hour_664,hour_665,hour_666,hour_667,hour_668,hour_669,hour_670,hour_671,hour_672,hour_673,hour_674,hour_675,hour_676,hour_677,hour_678,hour_679,hour_680,hour_681,hour_682,hour_683,hour_684,hour_685,hour_686,hour_687,hour_688,hour_689,hour_690,hour_691,hour_692,hour_693,hour_694,hour_695,hour_696,hour_697,hour_698,hour_699,hour_700,hour_701,hour_702,hour_703,hour_704,hour_705,hour_706,hour_707,hour_708,hour_709,hour_710,hour_711,hour_712,hour_713,hour_714,hour_715,hour_716,hour_717,hour_718,hour_719,hour_720
141400,010010201001,0,0,23,0,0,0,0,0,0,0,0,43,23,14,19,0,15,52,22,14,20,19,22,0,0,19,0,16,0,0,24,23,0,0,18,0,0,0,24,40,14,18,21,0,23,15,0,0,0,0,0,0,0,0,0,0,17,16,17,0,41,0,0,17,19,15,0,0,38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,14,0,19,0,0,0,24,0,0,0,0,0,20,0,0,0,20,14,0,33,17,0,0,22,15,0,16,39,0,42,0,0,0,0,0,0,0,20,0,15,39,23,0,0,22,23,21,0,18,19,14,34,43,0,0,0,0,38,0,0,0,0,0,0,0,16,0,0,0,0,0,42,0,0,39,62,14,77,0,0,0,0,0,0,0,0,0,18,0,0,0,0,0,38,20,0,21,22,21,40,36,0,15,0,0,0,0,0,0,16,0,0,0,0,0,20,0,23,24,21,0,0,19,43,40,56,15,0,0,0,0,0,0,19,0,21,0,0,0,0,0,0,21,40,40,0,24,41,0,0,0,24,0,19,0,0,0,0,0,18,0,23,0,24,22,15,15,0,19,0,34,18,43,0,0,0,0,0,19,0,0,0,0,15,0,37,24,0,23,23,0,0,0,0,58,16,0,0,0,0,0,0,0,0,0,0,0,0,0,39,17,14,0,0,0,21,41,57,52,41,15,33,0,0,0,0,0,0,0,0,0,0,0,22,60,18,0,23,23,0,21,56,0,0,60,0,0,0,0,0,0,0,0,0,0,0,0,0,24,23,0,0,20,15,0,42,0,24,21,38,36,20,0,0,0,0,0,0,0,0,0,0,38,0,0,33,0,33,0,24,16,24,20,0,0,0,0,0,0,0,0,24,38,22,0,23,91,74,117,71,73,109,74,98,21,35,20,0,0,16,0,0,0,0,0,0,0,0,0,0,22,0,43,0,0,0,15,0,0,0,18,0,0,16,0,0,0,0,0,0,19,0,0,0,0,0,0,40,18,0,14,0,24,15,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,0,17,0,0,55,14,0,0,22,0,0,0,0,0,0,0,0,19,0,0,0,14,0,0,22,0,14,72,18,0,0,33,0,0,0,36,19,0,0,0,0,0,0,0,0,20,0,0,43,0,0,0,0,20,20,41,60,0,0,0,17,0,0,0,0,0,0,0,0,14,0,0,0,0,40,0,40,19,14,20,77,0,0,0,0,0,0,0,0,0,0,0,0,0,21,16,38,131,23,98,0,20,0,0,57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33,17,37,18,0,20,40,0,0,16,42,21,0,15,0,0,0,0,0,0,0,59,0,0,0,23,35,16,0,40,0,16,17,36,41,19,23,17,0,0,0,0,0,0,0,0,0,0,0,0,35,0,19,0,24,0,0,39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,60,53,0,0,0,17,24,0,0,59,0,0,0,0,0,0,0,0,0,0,53,0,15,0,0,0,0,0,24,15,38,0,0,0,18,0,0,42,0,0,0,0,0,0,23,0,0,15,75,18,81,0,53,43,38,15,75,56,0,0,0,0
38756,010010201002,33,33,33,0,0,0,0,0,0,0,22,43,43,21,21,21,41,63,83,84,65,65,63,39,19,0,0,0,0,0,0,16,38,114,137,115,39,0,0,0,0,15,15,30,15,32,17,17,23,40,40,17,0,0,0,0,0,0,0,0,0,0,0,21,21,62,57,57,16,16,16,16,16,16,16,0,0,0,0,0,0,0,0,21,21,21,0,0,0,55,72,72,17,23,23,23,20,20,20,0,0,0,0,0,0,20,35,70,50,35,40,55,76,36,43,22,22,0,0,0,0,0,15,15,15,0,0,23,23,23,22,45,45,23,0,0,0,37,37,58,21,42,21,21,0,0,33,33,33,0,0,23,23,23,0,0,0,0,20,42,42,40,32,32,14,0,0,18,18,18,0,0,0,0,0,17,17,17,0,20,41,41,21,0,0,34,34,34,0,0,0,0,0,0,0,0,0,0,0,0,0,15,15,15,20,20,20,0,0,0,0,0,22,42,57,35,33,18,18,0,0,0,0,0,0,23,23,23,0,14,14,32,38,38,35,56,56,41,20,20,20,0,0,0,0,0,0,0,0,14,37,37,23,0,0,0,0,21,21,21,0,20,61,61,41,0,0,0,0,0,0,19,19,19,15,15,54,39,39,0,0,22,36,36,30,16,16,0,0,0,0,0,0,20,20,63,61,61,40,22,57,35,35,56,117,117,81,20,20,0,21,21,37,16,16,18,18,42,24,24,0,0,0,0,0,14,54,88,114,74,63,45,45,46,64,64,40,14,14,50,75,97,61,37,57,100,123,81,38,21,21,40,43,77,117,107,92,56,65,46,40,17,17,0,0,23,23,23,0,0,17,17,33,16,37,21,21,17,17,17,35,54,75,98,79,91,54,70,37,40,24,59,35,51,16,31,37,37,37,15,15,16,35,35,19,0,0,0,23,23,61,38,61,23,23,0,37,111,134,117,58,35,15,22,22,22,0,0,0,0,0,0,0,0,0,0,0,0,0,24,24,24,0,0,0,21,21,42,21,21,20,42,42,22,19,19,35,16,16,0,0,0,16,51,51,35,0,0,0,0,0,0,24,24,24,0,0,0,0,0,0,0,0,0,0,0,0,34,34,73,39,62,43,65,76,74,72,38,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19,39,39,36,16,16,18,39,39,21,0,19,19,19,0,0,0,0,0,0,0,18,33,33,36,21,21,0,16,16,40,24,24,0,0,0,19,19,19,0,0,0,0,0,0,0,0,18,18,18,0,0,0,24,24,24,20,20,20,15,15,15,22,22,22,0,0,0,0,0,62,98,98,36,0,0,0,0,24,24,24,0,0,16,16,16,0,0,0,0,16,30,30,14,0,0,58,58,58,0,0,14,36,60,46,24,0,0,0,0,0,0,0,0,0,0,0,14,14,14,21,21,21,0,22,22,22,14,14,14,24,24,24,0,19,19,19,0,0,0,0,17,17,31,34,73,59,39,0,19,19,36,33,53,36,20,0,0,22,43,43,21,0,24,24,59,35,35,0,0,16,16,16,0,0,18,18,18,0,0,0,0,19,19,19,0,0,0,0,0,0,0,21,21,21,0,17,17,17,14,14,38,24,41,17,17
169554,010010202001,14,24,0,0,0,0,0,0,0,16,0,19,16,0,18,0,22,37,0,0,23,0,22,24,0,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,43,0,0,0,0,0,16,23,0,0,0,0,0,0,24,0,0,0,24,15,43,17,15,0,0,17,0,0,0,0,42,0,0,0,0,24,0,23,15,0,0,0,0,17,17,17,59,36,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,0,20,24,0,16,0,0,0,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,0,14,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,23,0,0,21,20,0,33,37,24,24,0,0,0,0,0,0,0,14,0,0,0,0,17,0,0,0,0,23,0,0,0,39,0,0,21,0,0,0,0,0,0,0,0,0,0,0,38,0,20,16,19,42,23,0,37,18,0,0,0,0,0,0,0,0,0,0,0,0,0,20,19,24,0,0,23,57,16,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,0,17,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,24,17,36,41,0,0,24,0,0,0,0,0,0,0,17,0,0,16,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,23,0,0,95,55,0,0,0,0,15,39,0,0,0,0,0,0,0,22,20,19,24,14,16,14,0,0,19,24,19,0,0,0,21,0,21,0,0,0,0,0,0,0,0,20,16,0,24,17,16,15,0,0,0,14,19,0,0,23,0,0,0,19,0,0,0,0,0,0,16,21,21,38,22,34,19,0,17,14,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,0,18,16,0,41,0,0,0,23,19,0,0,0,0,0,21,0,0,0,0,0,0,16,33,19,23,14,0,0,0,0,38,0,39,0,0,0,0,0,0,0,0,0,0,0,0,18,0,0,0,33,0,0,43,23,52,36,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0,21,18,0,0,35,20,24,59,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,18,22,53,0,0,20,14,23,0,20,0,23,0,14,0,0,0,0,0,0,0,0,0,0,22,0,43,36,0,21,39,0,40,0,0,0,22,0,0,0,0,0,0,0,0,0,0,0,22,0,36,21,16,19,17,37,0,23,42,37,14,24,0,0,0,0,0,0,0,0,0,18,0,0,40,15,0,14,21,21,0,0,0,20,0,0,0,0,0,18,0,0,0,0,0,0,0,0,14,35,0,23,20,0,21,40,0,0,22,0,0,0,0,0,0,0,0,0,0,18,18,0,0,0,16,0,14,0,0,33,21,0,0,0,19,0,0,0,0,0,0,0,0,19,0,16,37,16,19,35,24,0,0,0,16,40,21,17,0,0,19,0,0,0,0,0,0,0,0,0,0,0,20,23,52,42,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,36,0,20,0,16,16,15,36,60,60,0,0,0,0
117119,010010202002,92,20,0,0,0,14,0,153,95,42,61,42,21,52,60,38,72,75,132,33,0,14,42,22,22,0,0,0,0,0,0,78,73,58,138,75,136,54,0,39,95,34,0,21,0,0,71,0,0,0,0,0,0,14,0,17,54,59,57,54,57,55,59,42,42,92,15,20,16,0,0,0,0,24,39,0,0,0,0,35,109,58,97,110,36,118,62,0,43,0,42,21,77,0,0,0,0,0,0,0,0,43,0,0,43,34,71,52,38,16,22,132,20,112,39,36,0,0,16,19,0,0,0,0,0,24,0,129,52,150,58,0,56,188,90,155,76,33,61,59,0,0,0,0,0,0,0,0,0,0,0,110,33,114,0,100,92,21,72,71,138,78,75,80,73,0,0,0,0,0,0,0,0,0,15,58,77,77,55,186,55,56,38,196,42,134,109,19,41,0,0,0,19,0,0,0,0,0,0,41,110,38,73,76,0,33,96,36,24,34,36,35,40,0,0,22,21,0,20,0,0,0,0,53,0,18,16,38,78,76,53,60,22,41,18,33,40,14,0,0,0,0,0,23,0,0,19,24,154,196,55,60,56,41,39,0,18,0,0,0,42,0,0,0,0,0,0,0,0,14,37,54,60,0,100,114,95,79,38,114,21,0,113,0,17,0,20,0,0,0,0,0,0,0,0,72,138,139,156,80,73,41,20,81,71,57,169,75,0,0,0,0,0,0,0,0,0,0,0,18,133,112,154,158,35,36,0,43,42,0,0,16,0,0,0,0,0,0,0,0,0,0,0,41,61,75,90,97,136,36,35,58,52,79,136,91,90,52,33,0,0,0,0,0,0,21,0,43,158,234,153,115,54,100,0,62,42,75,151,154,14,61,0,0,0,0,0,0,0,14,0,62,23,38,54,34,263,22,21,0,58,0,43,53,43,0,15,0,34,0,0,0,0,0,0,40,98,215,98,36,115,57,36,117,42,15,78,52,0,23,0,0,21,0,0,0,0,37,42,16,60,24,43,33,60,42,43,17,17,0,0,0,0,15,0,0,0,0,0,0,0,0,0,52,94,43,81,20,129,210,77,130,119,234,171,151,72,22,0,24,17,0,0,0,0,0,0,55,61,21,115,33,114,188,96,0,79,99,62,77,34,19,0,0,0,0,0,0,0,53,0,52,0,16,76,43,152,90,133,116,38,98,96,78,22,0,0,0,14,0,0,0,0,15,22,95,109,24,0,308,153,38,138,117,16,135,95,154,117,42,60,0,0,0,0,0,0,0,0,24,15,0,39,73,157,52,116,118,41,133,94,97,52,81,119,16,20,14,20,20,0,38,59,131,192,215,91,99,148,100,35,14,0,0,0,43,16,36,0,0,0,0,0,0,0,0,56,117,113,110,148,112,71,73,35,137,95,43,55,21,40,60,0,0,0,0,0,0,0,21,0,151,38,172,129,173,56,55,22,54,43,79,75,41,0,0,0,0,0,0,0,0,23,0,36,116,54,133,133,249,18,20,99,61,20,33,60,55,38,16,0,0,0,0,0,0,24,39,94,175,72,215,150,109,132,78,172,53,79,59,0,58,34,34,14,14,42,0,0,0,0,0,0,94,151,91,153,36,53,115,155,77,37,21,95,92,80,53,35,77
141640,010010203001,33,0,0,0,0,0,0,24,41,17,58,97,79,40,62,80,58,64,76,52,60,80,81,85,48,24,0,0,0,20,20,14,48,34,0,0,78,136,101,43,60,121,139,102,97,92,54,35,36,36,0,0,0,36,36,0,0,18,51,33,53,124,131,119,96,59,41,19,22,22,0,22,22,14,14,19,19,35,35,16,68,52,17,54,72,76,65,65,94,67,32,18,37,37,18,18,61,61,0,0,22,63,80,60,40,39,63,43,21,35,14,41,119,93,92,97,20,37,37,0,14,14,16,16,0,0,14,89,98,23,20,20,0,21,40,53,53,118,172,112,93,54,0,0,0,0,0,0,0,22,22,17,60,43,0,0,75,165,161,90,112,133,60,37,52,51,16,41,102,61,0,0,0,0,0,0,14,35,21,18,58,40,18,37,118,172,130,109,182,188,76,18,43,64,21,0,0,0,0,0,0,0,0,0,0,16,56,59,19,56,136,136,80,44,40,37,53,36,0,0,0,0,0,0,23,38,124,151,100,139,116,109,88,75,83,77,116,61,22,22,14,14,0,33,33,35,35,18,60,58,78,198,195,189,203,107,91,81,24,60,118,73,31,16,24,40,16,0,22,22,17,31,36,22,36,136,117,55,72,55,21,43,80,80,43,0,24,60,36,0,0,0,0,0,41,41,24,24,14,76,97,51,53,61,76,89,37,0,16,33,17,0,14,14,0,18,58,57,50,47,69,96,121,135,92,37,33,50,95,190,225,174,142,121,40,0,17,17,24,24,14,28,38,42,34,16,0,58,75,71,54,14,14,14,14,37,97,84,40,40,24,0,0,0,0,60,79,61,76,54,53,71,38,18,18,23,60,306,558,669,547,186,19,0,23,37,14,0,0,20,44,154,439,594,593,673,515,379,424,535,608,384,194,116,62,24,0,0,23,56,33,0,0,18,39,98,155,136,77,117,217,289,211,41,14,37,77,68,73,77,52,34,38,55,34,17,22,22,0,0,17,17,0,0,21,101,80,15,15,58,77,19,24,63,39,0,39,39,0,0,24,24,15,15,34,58,42,55,55,71,93,56,78,124,99,77,58,41,40,17,0,36,52,16,0,0,17,17,60,60,41,55,29,35,36,16,15,90,93,38,79,77,58,40,15,15,0,0,15,38,23,61,85,161,236,218,194,75,95,136,63,36,14,43,57,33,19,18,35,17,0,0,0,0,0,39,197,254,177,218,312,248,166,155,97,35,39,100,61,22,22,0,36,36,23,65,59,31,14,23,101,192,283,278,144,55,78,149,188,97,79,154,156,95,14,0,21,21,0,0,23,46,38,67,87,53,51,167,152,99,171,147,135,137,81,65,84,41,0,24,58,34,0,0,14,48,34,0,22,22,14,14,55,116,97,50,85,104,68,52,72,74,40,38,34,17,18,18,0,14,52,38,35,70,111,76,16,51,96,116,97,153,154,66,83,60,0,0,41,41,14,28,14,0,0,20,44,24,0,0,18,37,52,110,117,196,175,40,59,52,14,0,0,0,17,17,0,0,18,56,95,57,24,101,94,51,88,70,68,52,80,103,79,97,62,58,37,19,19,0,0,0,16,35,19,14,36,65,77,34,54,131,119,56,50,59,37,47,50,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [19]:
print("Adjustted total stop by dwelling time from CBG and national level (should be the same:")
print(adjusted_dwelling_time_stop_CBG_df[hourly_columns].sum().sum(),  adjusted_dwelling_time_stop_natinol_df.sum().sum())

Adjustted total stop by dwelling time from CBG and national level (should be the same:
5196196864 5196196864

In [20]:
# Save CSV files
adjusted_dwelling_time_stop_natinol_df.to_csv(adjusted_dwelling_time_stop_natinol_fname, index=False)
print("Saved national hourly stop at:", adjusted_dwelling_time_stop_natinol_fname)

adjusted_dwelling_time_stop_CBG_df.to_csv(adjusted_dwelling_time_stop_CBG_fname, index=False)
print("Saved CBG hourly stop at:", adjusted_dwelling_time_stop_CBG_fname)

Saved national hourly stop at: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\adjusted_dwelling_time_stop_natinol_2023_06.csv
Saved CBG hourly stop at: D:\OneDrive_PSU\OneDrive - The Pennsylvania State University\Research_doc\Wild_fire\hourly_map_test\adjusted_dwelling_time_stop_CBG_f_2023_06.csv

###  Convert observed stop counts to actual visitor counts.

#### compute the person_per_device at CBG and county level

Load ACS and home panel data, merge them into device sampling rate table at CBG and county level

In [33]:
ACS_df = pd.read_csv(ACS_file)
ACS_df["CBG_FIPS"] = ACS_df["fips"].astype(str).str.zfill(12)
print("Total US population (million):",  ACS_df['totalpopulation'].sum() / 1000000)

Total US population (million): 328.016242

In [38]:
print("Loading home panel file:", home_panel_fname)
panel_df = pd.read_csv(home_panel_fname)
target_panel_df = panel_df.query(f"YEAR == {year} and MON == {int(month)} and ISO_COUNTRY_CODE == 'US' ")
target_panel_df

Loading home panel file: F:\SafeGraph\Advan_2023_API\Monthly_Patterns_home_panel_summary\Monthly_Patterns_home_panel_summary_2019_2023.csv

,YEAR,MON,REGION,ISO_COUNTRY_CODE,CENSUS_BLOCK_GROUP,NUMBER_DEVICES_RESIDING,NUMBER_DEVICES_PRIMARY_DAYTIME
547544,2023,6,AK,US,020200013002,18.0,NaN
547545,2023,6,AK,US,021880001005,6.0,NaN
547546,2023,6,AK,US,020900011001,664.0,768.0
547547,2023,6,AK,US,021880002003,6.0,6.0
547548,2023,6,AK,US,021100002002,18.0,6.0
...,...,...,...,...,...,...,...
812375,2023,6,WY,US,560050004001,268.0,250.0
812376,2023,6,WY,US,560250005012,286.0,250.0
812377,2023,6,WY,US,560319594001,195.0,250.0
812378,2023,6,WY,US,560099566002,225.0,250.0
812379,2023,6,WY,US,560099566001,524.0,506.0

In [49]:
panel_ACS_df = target_panel_df.merge(ACS_df[['CBG_FIPS', 'totalpopulation']], left_on='CENSUS_BLOCK_GROUP', right_on='CBG_FIPS')
panel_ACS_df = panel_ACS_df.dropna(subset='NUMBER_DEVICES_RESIDING')
panel_ACS_df['NUMBER_DEVICES_RESIDING'] = panel_ACS_df['NUMBER_DEVICES_RESIDING'].astype(int)
panel_ACS_df = panel_ACS_df.sort_values('CBG_FIPS')
panel_ACS_df['person_per_device'] = panel_ACS_df['totalpopulation'] / panel_ACS_df['NUMBER_DEVICES_RESIDING']
print("Data cover US population:", panel_ACS_df['totalpopulation'].sum())
panel_ACS_df

Data cover US population: 327227353

,YEAR,MON,REGION,ISO_COUNTRY_CODE,CENSUS_BLOCK_GROUP,NUMBER_DEVICES_RESIDING,NUMBER_DEVICES_PRIMARY_DAYTIME,CBG_FIPS,totalpopulation,person_per_device
1248,2023,6,AL,US,010010201001,61,54.0,010010201001,730,11.967213
1991,2023,6,AL,US,010010201002,134,97.0,010010201002,1263,9.425373
1152,2023,6,AL,US,010010202001,42,48.0,010010202001,835,19.880952
2905,2023,6,AL,US,010010202002,85,158.0,010010202002,1124,13.223529
934,2023,6,AL,US,010010203001,274,286.0,010010203001,2774,10.124088
...,...,...,...,...,...,...,...,...,...,...
175266,2023,6,PR,US,721537506011,73,85.0,721537506011,883,12.095890
176252,2023,6,PR,US,721537506012,244,189.0,721537506012,2523,10.340164
175558,2023,6,PR,US,721537506013,134,103.0,721537506013,991,7.395522
175994,2023,6,PR,US,721537506021,122,146.0,721537506021,1577,12.926230
174889,2023,6,PR,US,721537506022,54,67.0,721537506022,648,12.000000

In [81]:
# get people_per_device of a county

panel_ACS_df['county_FIPS'] = panel_ACS_df['CBG_FIPS'].str[:5]
sampling_rate_county_df = panel_ACS_df.groupby(['county_FIPS'], as_index=False).agg(    # , 'YEAR', "MON", "REGION", "ISO_COUNTRY_CODE"
    county_device=('NUMBER_DEVICES_RESIDING', 'sum'),
    county_device_daytime=('NUMBER_DEVICES_RESIDING', 'sum'),
    county_device_population=('totalpopulation', 'sum'),
    ) 

sampling_rate_county_df['person_per_device_county'] = sampling_rate_county_df['county_device_population'] /  sampling_rate_county_df['county_device']

print("National device and population count:\n")
print(sampling_rate_county_df[['county_device', 'county_device_population']].sum())

people_per_device_df = panel_ACS_df.merge(sampling_rate_county_df, left_on='county_FIPS', right_on='county_FIPS')
people_per_device_df.to_csv(person_per_device_fname, index=False)
people_per_device_df

National device and population count:

county_device                45282809
county_device_population    327227353
dtype: int64

,YEAR,MON,REGION,ISO_COUNTRY_CODE,CENSUS_BLOCK_GROUP,NUMBER_DEVICES_RESIDING,NUMBER_DEVICES_PRIMARY_DAYTIME,CBG_FIPS,totalpopulation,person_per_device,county_FIPS,county_device,county_device_daytime,county_device_population,person_per_device_county
0,2023,6,AL,US,010010201001,61,54.0,010010201001,730,11.967213,01001,8252,8252,55380,6.711100
1,2023,6,AL,US,010010201002,134,97.0,010010201002,1263,9.425373,01001,8252,8252,55380,6.711100
2,2023,6,AL,US,010010202001,42,48.0,010010202001,835,19.880952,01001,8252,8252,55380,6.711100
3,2023,6,AL,US,010010202002,85,158.0,010010202002,1124,13.223529,01001,8252,8252,55380,6.711100
4,2023,6,AL,US,010010203001,274,286.0,010010203001,2774,10.124088,01001,8252,8252,55380,6.711100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219119,2023,6,PR,US,721537506011,73,85.0,721537506011,883,12.095890,72153,4885,4885,35428,7.252405
219120,2023,6,PR,US,721537506012,244,189.0,721537506012,2523,10.340164,72153,4885,4885,35428,7.252405
219121,2023,6,PR,US,721537506013,134,103.0,721537506013,991,7.395522,72153,4885,4885,35428,7.252405
219122,2023,6,PR,US,721537506021,122,146.0,721537506021,1577,12.926230,72153,4885,4885,35428,7.252405
219123,2023,6,PR,US,721537506022,54,67.0,721537506022,648,12.000000,72153,4885,4885,35428,7.252405

#### restore the observated stop count to actual visitor count

In [107]:
people_per_device_df = pd.read_csv(person_per_device_fname, dtype={'CBG_FIPS': str})
adjusted_dwelling_time_stop_CBG_df = pd.read_csv(adjusted_dwelling_time_stop_CBG_fname, dtype={'CBG': str})

In [76]:
adjusted_dwelling_time_stop_CBG_df
# people_per_device_df

,CBG,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,hour_9,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,hour_24,hour_25,hour_26,hour_27,hour_28,hour_29,hour_30,hour_31,hour_32,hour_33,hour_34,hour_35,hour_36,hour_37,hour_38,hour_39,hour_40,hour_41,hour_42,hour_43,hour_44,hour_45,hour_46,hour_47,hour_48,hour_49,hour_50,hour_51,hour_52,hour_53,hour_54,hour_55,hour_56,hour_57,hour_58,hour_59,hour_60,hour_61,hour_62,hour_63,hour_64,hour_65,hour_66,hour_67,hour_68,hour_69,hour_70,hour_71,hour_72,hour_73,hour_74,hour_75,hour_76,hour_77,hour_78,hour_79,hour_80,hour_81,hour_82,hour_83,hour_84,hour_85,hour_86,hour_87,hour_88,hour_89,hour_90,hour_91,hour_92,hour_93,hour_94,hour_95,hour_96,hour_97,hour_98,hour_99,hour_100,hour_101,hour_102,hour_103,hour_104,hour_105,hour_106,hour_107,hour_108,hour_109,hour_110,hour_111,hour_112,hour_113,hour_114,hour_115,hour_116,hour_117,hour_118,hour_119,hour_120,hour_121,hour_122,hour_123,hour_124,hour_125,hour_126,hour_127,hour_128,hour_129,hour_130,hour_131,hour_132,hour_133,hour_134,hour_135,hour_136,hour_137,hour_138,hour_139,hour_140,hour_141,hour_142,hour_143,hour_144,hour_145,hour_146,hour_147,hour_148,hour_149,hour_150,hour_151,hour_152,hour_153,hour_154,hour_155,hour_156,hour_157,hour_158,hour_159,hour_160,hour_161,hour_162,hour_163,hour_164,hour_165,hour_166,hour_167,hour_168,hour_169,hour_170,hour_171,hour_172,hour_173,hour_174,hour_175,hour_176,hour_177,hour_178,hour_179,hour_180,hour_181,hour_182,hour_183,hour_184,hour_185,hour_186,hour_187,hour_188,hour_189,hour_190,hour_191,hour_192,hour_193,hour_194,hour_195,hour_196,hour_197,hour_198,hour_199,hour_200,hour_201,hour_202,hour_203,hour_204,hour_205,hour_206,hour_207,hour_208,hour_209,hour_210,hour_211,hour_212,hour_213,hour_214,hour_215,hour_216,hour_217,hour_218,hour_219,hour_220,hour_221,hour_222,hour_223,hour_224,hour_225,hour_226,hour_227,hour_228,hour_229,hour_230,hour_231,hour_232,hour_233,hour_234,hour_235,hour_236,hour_237,hour_238,hour_239,hour_240,hour_241,hour_242,hour_243,hour_244,hour_245,hour_246,hour_247,hour_248,hour_249,hour_250,hour_251,hour_252,hour_253,hour_254,hour_255,hour_256,hour_257,hour_258,hour_259,hour_260,hour_261,hour_262,hour_263,hour_264,hour_265,hour_266,hour_267,hour_268,hour_269,hour_270,hour_271,hour_272,hour_273,hour_274,hour_275,hour_276,hour_277,hour_278,hour_279,hour_280,hour_281,hour_282,hour_283,hour_284,hour_285,hour_286,hour_287,hour_288,hour_289,hour_290,hour_291,hour_292,hour_293,hour_294,hour_295,hour_296,hour_297,hour_298,hour_299,hour_300,hour_301,hour_302,hour_303,hour_304,hour_305,hour_306,hour_307,hour_308,hour_309,hour_310,hour_311,hour_312,hour_313,hour_314,hour_315,hour_316,hour_317,hour_318,hour_319,hour_320,hour_321,hour_322,hour_323,hour_324,hour_325,hour_326,hour_327,hour_328,hour_329,hour_330,hour_331,hour_332,hour_333,hour_334,hour_335,hour_336,hour_337,hour_338,hour_339,hour_340,hour_341,hour_342,hour_343,hour_344,hour_345,hour_346,hour_347,hour_348,hour_349,hour_350,hour_351,hour_352,hour_353,hour_354,hour_355,hour_356,hour_357,hour_358,hour_359,hour_360,hour_361,hour_362,hour_363,hour_364,hour_365,hour_366,hour_367,hour_368,hour_369,hour_370,hour_371,hour_372,hour_373,hour_374,hour_375,hour_376,hour_377,hour_378,hour_379,hour_380,hour_381,hour_382,hour_383,hour_384,hour_385,hour_386,hour_387,hour_388,hour_389,hour_390,hour_391,hour_392,hour_393,hour_394,hour_395,hour_396,hour_397,hour_398,hour_399,hour_400,hour_401,hour_402,hour_403,hour_404,hour_405,hour_406,hour_407,hour_408,hour_409,hour_410,hour_411,hour_412,hour_413,hour_414,hour_415,hour_416,hour_417,hour_418,hour_419,hour_420,hour_421,hour_422,hour_423,hour_424,hour_425,hour_426,hour_427,hour_428,hour_429,hour_430,hour_431,hour_432,hour_433,hour_434,hour_435,hour_436,hour_437,hour_438,hour_439,hour_440,hour_441,hour_442,hour_443,hour_444,hour_445,hour_446,hour_447,hour_448,hour_449,hour_450,hour_451,hour_452,hour_453,hour_454,hour_455,hour_456,hour_457,hour_458,hour_459,hour_460,hour_461,hour_462,hour_463,hour_464,hour_465,hour_466,hour_467,hour_468,hour_469,hour_470,hour_471,hour_472,hour_473,hour_474,hour_475,hour_476,hour_477,hour_478,hour_479,hour_480,hour_481,hour_482,hour_483,hour_484,hour_485,hour_486,hour_487,hour_488,hour_489,hour_490,hour_491,hour_492,hour_493,hour_494,hour_495,hour_496,hour_497,hour_498,hour_499,hour_500,hour_501,hour_502,hour_503,hour_504,hour_505,hour_506,hour_507,hour_508,hour_509,hour_510,hour_511,hour_512,hour_513,hour_514,hour_515,hour_516,hour_517,hour_518,hour_519,hour_520,hour_521,hour_522,hour_523,hour_524,hour_525,hour_526,hour_527,hour_528,hour_529,hour_530,hour_531,hour_532,hour_533,hour_534,hour_535,hour_536,hour_537,hour_538,hour_539,hour_540,hour_541,hour_542,hour_543,hour_544,hour_545,hour_546,hour_547,hour_548,hour_549,hour_550,hour_551,hour_552,hour_553,hour_554,hour_555,hour_556,hour_557,hour_558,hour_559,hour_560,hour_561,hour_562,hour_563,hour_564,hour_565,hour_566,hour_567,hour_568,hour_569,hour_570,hour_571,hour_572,hour_573,hour_574,hour_575,hour_576,hour_577,hour_578,hour_579,hour_580,hour_581,hour_582,hour_583,hour_584,hour_585,hour_586,hour_587,hour_588,hour_589,hour_590,hour_591,hour_592,hour_593,hour_594,hour_595,hour_596,hour_597,hour_598,hour_599,hour_600,hour_601,hour_602,hour_603,hour_604,hour_605,hour_606,hour_607,hour_608,hour_609,hour_610,hour_611,hour_612,hour_613,hour_614,hour_615,hour_616,hour_617,hour_618,hour_619,hour_620,hour_621,hour_622,hour_623,hour_624,hour_625,hour_626,hour_627,hour_628,hour_629,hour_630,hour_631,hour_632,hour_633,hour_634,hour_635,hour_636,hour_637,hour_638,hour_639,hour_640,hour_641,hour_642,hour_643,hour_644,hour_645,hour_646,hour_647,hour_648,hour_649,hour_650,hour_651,hour_652,hour_653,hour_654,hour_655,hour_656,hour_657,hour_658,hour_659,hour_660,hour_661,hour_662,hour_663,hour_664,hour_665,hour_666,hour_667,hour_668,hour_669,hour_670,hour_671,hour_672,hour_673,hour_674,hour_675,hour_676,hour_677,hour_678,hour_679,hour_680,hour_681,hour_682,hour_683,hour_684,hour_685,hour_686,hour_687,hour_688,hour_689,hour_690,hour_691,hour_692,hour_693,hour_694,hour_695,hour_696,hour_697,hour_698,hour_699,hour_700,hour_701,hour_702,hour_703,hour_704,hour_705,hour_706,hour_707,hour_708,hour_709,hour_710,hour_711,hour_712,hour_713,hour_714,hour_715,hour_716,hour_717,hour_718,hour_719,hour_720
0,010010201001,0,0,23,0,0,0,0,0,0,0,0,43,23,14,19,0,15,52,22,14,20,19,22,0,0,19,0,16,0,0,24,23,0,0,18,0,0,0,24,40,14,18,21,0,23,15,0,0,0,0,0,0,0,0,0,0,17,16,17,0,41,0,0,17,19,15,0,0,38,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,0,0,14,0,19,0,0,0,24,0,0,0,0,0,20,0,0,0,20,14,0,33,17,0,0,22,15,0,16,39,0,42,0,0,0,0,0,0,0,20,0,15,39,23,0,0,22,23,21,0,18,19,14,34,43,0,0,0,0,38,0,0,0,0,0,0,0,16,0,0,0,0,0,42,0,0,39,62,14,77,0,0,0,0,0,0,0,0,0,18,0,0,0,0,0,38,20,0,21,22,21,40,36,0,15,0,0,0,0,0,0,16,0,0,0,0,0,20,0,23,24,21,0,0,19,43,40,56,15,0,0,0,0,0,0,19,0,21,0,0,0,0,0,0,21,40,40,0,24,41,0,0,0,24,0,19,0,0,0,0,0,18,0,23,0,24,22,15,15,0,19,0,34,18,43,0,0,0,0,0,19,0,0,0,0,15,0,37,24,0,23,23,0,0,0,0,58,16,0,0,0,0,0,0,0,0,0,0,0,0,0,39,17,14,0,0,0,21,41,57,52,41,15,33,0,0,0,0,0,0,0,0,0,0,0,22,60,18,0,23,23,0,21,56,0,0,60,0,0,0,0,0,0,0,0,0,0,0,0,0,24,23,0,0,20,15,0,42,0,24,21,38,36,20,0,0,0,0,0,0,0,0,0,0,38,0,0,33,0,33,0,24,16,24,20,0,0,0,0,0,0,0,0,24,38,22,0,23,91,74,117,71,73,109,74,98,21,35,20,0,0,16,0,0,0,0,0,0,0,0,0,0,22,0,43,0,0,0,15,0,0,0,18,0,0,16,0,0,0,0,0,0,19,0,0,0,0,0,0,40,18,0,14,0,24,15,0,0,0,0,0,0,0,0,0,0,0,0,0,23,0,0,17,0,0,55,14,0,0,22,0,0,0,0,0,0,0,0,19,0,0,0,14,0,0,22,0,14,72,18,0,0,33,0,0,0,36,19,0,0,0,0,0,0,0,0,20,0,0,43,0,0,0,0,20,20,41,60,0,0,0,17,0,0,0,0,0,0,0,0,14,0,0,0,0,40,0,40,19,14,20,77,0,0,0,0,0,0,0,0,0,0,0,0,0,21,16,38,131,23,98,0,20,0,0,57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,33,17,37,18,0,20,40,0,0,16,42,21,0,15,0,0,0,0,0,0,0,59,0,0,0,23,35,16,0,40,0,16,17,36,41,19,23,17,0,0,0,0,0,0,0,0,0,0,0,0,35,0,19,0,24,0,0,39,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,60,53,0,0,0,17,24,0,0,59,0,0,0,0,0,0,0,0,0,0,53,0,15,0,0,0,0,0,24,15,38,0,0,0,18,0,0,42,0,0,0,0,0,0,23,0,0,15,75,18,81,0,53,43,38,15,75,56,0,0,0,0
1,010010201002,33,33,33,0,0,0,0,0,0,0,22,43,43,21,21,21,41,63,83,84,65,65,63,39,19,0,0,0,0,0,0,16,38,114,137,115,39,0,0,0,0,15,15,30,15,32,17,17,23,40,40,17,0,0,0,0,0,0,0,0,0,0,0,21,21,62,57,57,16,16,16,16,16,16,16,0,0,0,0,0,0,0,0,21,21,21,0,0,0,55,72,72,17,23,23,23,20,20,20,0,0,0,0,0,0,20,35,70,50,35,40,55,76,36,43,22,22,0,0,0,0,0,15,15,15,0,0,23,23,23,22,45,45,23,0,0,0,37,37,58,21,42,21,21,0,0,33,33,33,0,0,23,23,23,0,0,0,0,20,42,42,40,32,32,14,0,0,18,18,18,0,0,0,0,0,17,17,17,0,20,41,41,21,0,0,34,34,34,0,0,0,0,0,0,0,0,0,0,0,0,0,15,15,15,20,20,20,0,0,0,0,0,22,42,57,35,33,18,18,0,0,0,0,0,0,23,23,23,0,14,14,32,38,38,35,56,56,41,20,20,20,0,0,0,0,0,0,0,0,14,37,37,23,0,0,0,0,21,21,21,0,20,61,61,41,0,0,0,0,0,0,19,19,19,15,15,54,39,39,0,0,22,36,36,30,16,16,0,0,0,0,0,0,20,20,63,61,61,40,22,57,35,35,56,117,117,81,20,20,0,21,21,37,16,16,18,18,42,24,24,0,0,0,0,0,14,54,88,114,74,63,45,45,46,64,64,40,14,14,50,75,97,61,37,57,100,123,81,38,21,21,40,43,77,117,107,92,56,65,46,40,17,17,0,0,23,23,23,0,0,17,17,33,16,37,21,21,17,17,17,35,54,75,98,79,91,54,70,37,40,24,59,35,51,16,31,37,37,37,15,15,16,35,35,19,0,0,0,23,23,61,38,61,23,23,0,37,111,134,117,58,35,15,22,22,22,0,0,0,0,0,0,0,0,0,0,0,0,0,24,24,24,0,0,0,21,21,42,21,21,20,42,42,22,19,19,35,16,16,0,0,0,16,51,51,35,0,0,0,0,0,0,24,24,24,0,0,0,0,0,0,0,0,0,0,0,0,34,34,73,39,62,43,65,76,74,72,38,20,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,19,39,39,36,16,16,18,39,39,21,0,19,19,19,0,0,0,0,0,0,0,18,33,33,36,21,21,0,16,16,40,24,24,0,0,0,19,19,19,0,0,0,0,0,0,0,0,18,18,18,0,0,0,24,24,24,20,20,20,15,15,15,22,22,22,0,0,0,0,0,62,98,98,36,0,0,0,0,24,24,24,0,0,16,16,16,0,0,0,0,16,30,30,14,0,0,58,58,58,0,0,14,36,60,46,24,0,0,0,0,0,0,0,0,0,0,0,14,14,14,21,21,21,0,22,22,22,14,14,14,24,24,24,0,19,19,19,0,0,0,0,17,17,31,34,73,59,39,0,19,19,36,33,53,36,20,0,0,22,43,43,21,0,24,24,59,35,35,0,0,16,16,16,0,0,18,18,18,0,0,0,0,19,19,19,0,0,0,0,0,0,0,21,21,21,0,17,17,17,14,14,38,24,41,17,17
2,010010202001,14,24,0,0,0,0,0,0,0,16,0,19,16,0,18,0,22,37,0,0,23,0,22,24,0,0,0,0,0,0,0,23,0,0,0,0,0,0,0,0,0,0,43,0,0,0,0,0,16,23,0,0,0,0,0,0,24,0,0,0,24,15,43,17,15,0,0,17,0,0,0,0,42,0,0,0,0,24,0,23,15,0,0,0,0,17,17,17,59,36,0,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,0,20,24,0,16,0,0,0,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,21,0,14,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24,23,0,0,21,20,0,33,37,24,24,0,0,0,0,0,0,0,14,0,0,0,0,17,0,0,0,0,23,0,0,0,39,0,0,21,0,0,0,0,0,0,0,0,0,0,0,38,0,20,16,19,42,23,0,37,18,0,0,0,0,0,0,0,0,0,0,0,0,0,20,19,24,0,0,23,57,16,0,0,0,0,0,14,0,0,0,0,0,0,0,0,0,0,0,21,0,0,0,0,0,0,0,17,18,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22,24,17,36,41,0,0,24,0,0,0,0,0,0,0,17,0,0,16,19,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,0,0,0,0,0,0,23,0,0,95,55,0,0,0,0,15,39,0,0,0,0,0,0,0,22,20,19,24,14,16,14,0,0,19,24,19,0,0,0,21,0,21,0,0,0,0,0,0,0,0,20,16,0,24,17,16,15,0,0,0,14,19,0,0,23,0,0,0,19,0,0,0,0,0,0,16,21,21,38,22,34,19,0,17,14,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,34,0,18,16,0,41,0,0,0,23,19,0,0,0,0,0,21,0,0,0,0,0,0,16,33,19,23,14,0,0,0,0,38,0,39,0,0,0,0,0,0,0,0,0,0,0,0,18,0,0,0,33,0,0,43,23,52,36,0,0,0,0,0,0,0,0,0,0,0,0,0,22,0,21,18,0,0,35,20,24,59,0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,18,22,53,0,0,20,14,23,0,20,0,23,0,14,0,0,0,0,0,0,0,0,0,0,22,0,43,36,0,21,39,0,40,0,0,0,22,0,0,0,0,0,0,0,0,0,0,0,22,0,36,21,16,19,17,37,0,23,42,37,14,24,0,0,0,0,0,0,0,0,0,18,0,0,40,15,0,14,21,21,0,0,0,20,0,0,0,0,0,18,0,0,0,0,0,0,0,0,14,35,0,23,20,0,21,40,0,0,22,0,0,0,0,0,0,0,0,0,0,18,18,0,0,0,16,0,14,0,0,33,21,0,0,0,19,0,0,0,0,0,0,0,0,19,0,16,37,16,19,35,24,0,0,0,16,40,21,17,0,0,19,0,0,0,0,0,0,0,0,0,0,0,20,23,52,42,0,21,0,0,0,0,0,0,0,0,0,0,0,0,0,0,14,36,0,20,0,16,16,15,36,60,60,0,0,0,0
3,010010202002,92,20,0,0,0,14,0,153,95,42,61,42,21,52,60,38,72,75,132,33,0,14,42,22,22,0,0,0,0,0,0,78,73,58,138,75,136,54,0,39,95,34,0,21,0,0,71,0,0,0,0,0,0,14,0,17,54,59,57,54,57,55,59,42,42,92,15,20,16,0,0,0,0,24,39,0,0,0,0,35,109,58,97,110,36,118,62,0,43,0,42,21,77,0,0,0,0,0,0,0,0,43,0,0,43,34,71,52,38,16,22,132,20,112,39,36,0,0,16,19,0,0,0,0,0,24,0,129,52,150,58,0,56,188,90,155,76,33,61,59,0,0,0,0,0,0,0,0,0,0,0,110,33,114,0,100,92,21,72,71,138,78,75,80,73,0,0,0,0,0,0,0,0,0,15,58,77,77,55,186,55,56,38,196,42,134,109,19,41,0,0,0,19,0,0,0,0,0,0,41,110,38,73,76,0,33,96,36,24,34,36,35,40,0,0,22,21,0,20,0,0,0,0,53,0,18,16,38,78,76,53,60,22,41,18,33,40,14,0,0,0,0,0,23,0,0,19,24,154,196,55,60,56,41,39,0,18,0,0,0,42,0,0,0,0,0,0,0,0,14,37,54,60,0,100,114,95,79,38,114,21,0,113,0,17,0,20,0,0,0,0,0,0,0,0,72,138,139,156,80,73,41,20,81,71,57,169,75,0,0,0,0,0,0,0,0,0,0,0,18,133,112,154,158,35,36,0,43,42,0,0,16,0,0,0,0,0,0,0,0,0,0,0,41,61,75,90,97,136,36,35,58,52,79,136,91,90,52,33,0,0,0,0,0,0,21,0,43,158,234,153,115,54,100,0,62,42,75,151,154,14,61,0,0,0,0,0,0,0,14,0,62,23,38,54,34,263,22,21,0,58,0,43,53,43,0,15,0,34,0,0,0,0,0,0,40,98,215,98,36,115,57,36,117,42,15,78,52,0,23,0,0,21,0,0,0,0,37,42,16,60,24,43,33,60,42,43,17,17,0,0,0,0,15,0,0,0,0,0,0,0,0,0,52,94,43,81,20,129,210,77,130,119,234,171,151,72,22,0,24,17,0,0,0,0,0,0,55,61,21,115,33,114,188,96,0,79,99,62,77,34,19,0,0,0,0,0,0,0,53,0,52,0,16,76,43,152,90,133,116,38,98,96,78,22,0,0,0,14,0,0,0,0,15,22,95,109,24,0,308,153,38,138,117,16,135,95,154,117,42,60,0,0,0,0,0,0,0,0,24,15,0,39,73,157,52,116,118,41,133,94,97,52,81,119,16,20,14,20,20,0,38,59,131,192,215,91,99,148,100,35,14,0,0,0,43,16,36,0,0,0,0,0,0,0,0,56,117,113,110,148,112,71,73,35,137,95,43,55,21,40,60,0,0,0,0,0,0,0,21,0,151,38,172,129,173,56,55,22,54,43,79,75,41,0,0,0,0,0,0,0,0,23,0,36,116,54,133,133,249,18,20,99,61,20,33,60,55,38,16,0,0,0,0,0,0,24,39,94,175,72,215,150,109,132,78,172,53,79,59,0,58,34,34,14,14,42,0,0,0,0,0,0,94,151,91,153,36,53,115,155,77,37,21,95,92,80,53,35,77
4,010010203001,33,0,0,0,0,0,0,24,41,17,58,97,79,40,62,80,58,64,76,52,60,80,81,85,48,24,0,0,0,20,20,14,48,34,0,0,78,136,101,43,60,121,139,102,97,92,54,35,36,36,0,0,0,36,36,0,0,18,51,33,53,124,131,119,96,59,41,19,22,22,0,22,22,14,14,19,19,35,35,16,68,52,17,54,72,76,65,65,94,67,32,18,37,37,18,18,61,61,0,0,22,63,80,60,40,39,63,43,21,35,14,41,119,93,92,97,20,37,37,0,14,14,16,16,0,0,14,89,98,23,20,20,0,21,40,53,53,118,172,112,93,54,0,0,0,0,0,0,0,22,22,17,60,43,0,0,75,165,161,90,112,133,60,37,52,51,16,41,102,61,0,0,0,0,0,0,14,35,21,18,58,40,18,37,118,172,130,109,182,188,76,18,43,64,21,0,0,0,0,0,0,0,0,0,0,16,56,59,19,56,136,136,80,44,40,37,53,36,0,0,0,0,0,0,23,38,124,151,100,139,116,109,88,75,83,77,116,61,22,22,14,14,0,33,33,35,35,18,60,58,78,198,195,189,203,107,91,81,24,60,118,73,31,16,24,40,16,0,22,22,17,31,36,22,36,136,117,55,72,55,21,43,80,80,43,0,24,60,36,0,0,0,0,0,41,41,24,24,14,76,97,51,53,61,76,89,37,0,16,33,17,0,14,14,0,18,58,57,50,47,69,96,121,135,92,37,33,50,95,190,225,174,142,121,40,0,17,17,24,24,14,28,38,42,34,16,0,58,75,71,54,14,14,14,14,37,97,84,40,40,24,0,0,0,0,60,79,61,76,54,53,71,38,18,18,23,60,306,558,669,547,186,19,0,23,37,14,0,0,20,44,154,439,594,593,673,515,379,424,535,608,384,194,116,62,24,0,0,23,56,33,0,0,18,39,98,155,136,77,117,217,289,211,41,14,37,77,68,73,77,52,34,38,55,34,17,22,22,0,0,17,17,0,0,21,101,80,15,15,58,77,19,24,63,39,0,39,39,0,0,24,24,15,15,34,58,42,55,55,71,93,56,78,124,99,77,58,41,40,17,0,36,52,16,0,0,17,17,60,60,41,55,29,35,36,16,15,90,93,38,79,77,58,40,15,15,0,0,15,38,23,61,85,161,236,218,194,75,95,136,63,36,14,43,57,33,19,18,35,17,0,0,0,0,0,39,197,254,177,218,312,248,166,155,97,35,39,100,61,22,22,0,36,36,23,65,59,31,14,23,101,192,283,278,144,55,78,149,188,97,79,154,156,95,14,0,21,21,0,0,23,46,38,67,87,53,51,167,152,99,171,147,135,137,81,65,84,41,0,24,58,34,0,0,14,48,34,0,22,22,14,14,55,116,97,50,85,104,68,52,72,74,40,38,34,17,18,18,0,14,52,38,35,70,111,76,16,51,96,116,97,153,154,66,83,60,0,0,41,41,14,28,14,0,0,20,44,24,0,0,18,37,52,110,117,196,175,40,59,52,14,0,0,0,17,17,0,0,18,56,95,57,24,101,94,51,88,70,68,52,80,103,79,97,62,58,37,19,19,0,0,0,16,35,19,14,36,65,77,34,54,131,119,56,50,59,37,47,50,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...

In [78]:
adjusted_dwelling_time_stop_CBG_df.shape

(220684, 721)

In [135]:
# Assume a stop is a device
hour_cnt = adjusted_dwelling_time_stop_CBG_df.shape[1] - 1


hourly_stop_sampling_rate_df = adjusted_dwelling_time_stop_CBG_df.merge(people_per_device_df, left_on='CBG', right_on='CBG_FIPS')
national_people_per_device = hourly_stop_sampling_rate_df['totalpopulation'].sum() / hourly_stop_sampling_rate_df['NUMBER_DEVICES_RESIDING'].sum()

print("hour_cnt:", hour_cnt)
print("national_people_per_device:", national_people_per_device)

for h in range(hour_cnt):
    hourly_stop_sampling_rate_df.iloc[:, h + 1] = hourly_stop_sampling_rate_df.iloc[:, h + 1] * hourly_stop_sampling_rate_df['person_per_device']   # CBG leval
    # hourly_stop_sampling_rate_df.iloc[:, h + 1] = hourly_stop_sampling_rate_df.iloc[:, h + 1] * national_people_per_device    # national leval
    # hourly_stop_sampling_rate_df.iloc[:, h + 1] = hourly_stop_sampling_rate_df.iloc[:, h + 1] * hourly_stop_sampling_rate_df['person_per_device_county']   # county level
    

## used      CBG level sampling rate: 51028323628.24674
## used   county level sampling rate: 51223351774.32022   # increase 0.3%
## used national level sampling rate: 37518194037.32022   # decrease 26.5%

restored_actual_CBG_hourly_visitor_df = hourly_stop_sampling_rate_df.iloc[:, :hour_cnt + 1]

print("Restored total visitor count (billion):")
print(restored_actual_CBG_hourly_visitor_df.iloc[:, 1:hour_cnt + 1].sum().sum() / 1000000000)  # used CBG level sampling rate: 51028323628.24674

print("Restored total visitor dataframe shape:",  restored_actual_CBG_hourly_visitor_df.shape)

hour_cnt: 720
national_people_per_device: 7.226305160482226
Restored total visitor count (billion):
51.028323628246746
Restored total visitor dataframe shape: (219123, 721)

In [136]:
restored_actual_CBG_hourly_visitor_df

,CBG,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,hour_9,hour_10,hour_11,hour_12,hour_13,hour_14,hour_15,hour_16,hour_17,hour_18,hour_19,hour_20,hour_21,hour_22,hour_23,hour_24,hour_25,hour_26,hour_27,hour_28,hour_29,hour_30,hour_31,hour_32,hour_33,hour_34,hour_35,hour_36,hour_37,hour_38,hour_39,hour_40,hour_41,hour_42,hour_43,hour_44,hour_45,hour_46,hour_47,hour_48,hour_49,hour_50,hour_51,hour_52,hour_53,hour_54,hour_55,hour_56,hour_57,hour_58,hour_59,hour_60,hour_61,hour_62,hour_63,hour_64,hour_65,hour_66,hour_67,hour_68,hour_69,hour_70,hour_71,hour_72,hour_73,hour_74,hour_75,hour_76,hour_77,hour_78,hour_79,hour_80,hour_81,hour_82,hour_83,hour_84,hour_85,hour_86,hour_87,hour_88,hour_89,hour_90,hour_91,hour_92,hour_93,hour_94,hour_95,hour_96,hour_97,hour_98,hour_99,hour_100,hour_101,hour_102,hour_103,hour_104,hour_105,hour_106,hour_107,hour_108,hour_109,hour_110,hour_111,hour_112,hour_113,hour_114,hour_115,hour_116,hour_117,hour_118,hour_119,hour_120,hour_121,hour_122,hour_123,hour_124,hour_125,hour_126,hour_127,hour_128,hour_129,hour_130,hour_131,hour_132,hour_133,hour_134,hour_135,hour_136,hour_137,hour_138,hour_139,hour_140,hour_141,hour_142,hour_143,hour_144,hour_145,hour_146,hour_147,hour_148,hour_149,hour_150,hour_151,hour_152,hour_153,hour_154,hour_155,hour_156,hour_157,hour_158,hour_159,hour_160,hour_161,hour_162,hour_163,hour_164,hour_165,hour_166,hour_167,hour_168,hour_169,hour_170,hour_171,hour_172,hour_173,hour_174,hour_175,hour_176,hour_177,hour_178,hour_179,hour_180,hour_181,hour_182,hour_183,hour_184,hour_185,hour_186,hour_187,hour_188,hour_189,hour_190,hour_191,hour_192,hour_193,hour_194,hour_195,hour_196,hour_197,hour_198,hour_199,hour_200,hour_201,hour_202,hour_203,hour_204,hour_205,hour_206,hour_207,hour_208,hour_209,hour_210,hour_211,hour_212,hour_213,hour_214,hour_215,hour_216,hour_217,hour_218,hour_219,hour_220,hour_221,hour_222,hour_223,hour_224,hour_225,hour_226,hour_227,hour_228,hour_229,hour_230,hour_231,hour_232,hour_233,hour_234,hour_235,hour_236,hour_237,hour_238,hour_239,hour_240,hour_241,hour_242,hour_243,hour_244,hour_245,hour_246,hour_247,hour_248,hour_249,hour_250,hour_251,hour_252,hour_253,hour_254,hour_255,hour_256,hour_257,hour_258,hour_259,hour_260,hour_261,hour_262,hour_263,hour_264,hour_265,hour_266,hour_267,hour_268,hour_269,hour_270,hour_271,hour_272,hour_273,hour_274,hour_275,hour_276,hour_277,hour_278,hour_279,hour_280,hour_281,hour_282,hour_283,hour_284,hour_285,hour_286,hour_287,hour_288,hour_289,hour_290,hour_291,hour_292,hour_293,hour_294,hour_295,hour_296,hour_297,hour_298,hour_299,hour_300,hour_301,hour_302,hour_303,hour_304,hour_305,hour_306,hour_307,hour_308,hour_309,hour_310,hour_311,hour_312,hour_313,hour_314,hour_315,hour_316,hour_317,hour_318,hour_319,hour_320,hour_321,hour_322,hour_323,hour_324,hour_325,hour_326,hour_327,hour_328,hour_329,hour_330,hour_331,hour_332,hour_333,hour_334,hour_335,hour_336,hour_337,hour_338,hour_339,hour_340,hour_341,hour_342,hour_343,hour_344,hour_345,hour_346,hour_347,hour_348,hour_349,hour_350,hour_351,hour_352,hour_353,hour_354,hour_355,hour_356,hour_357,hour_358,hour_359,hour_360,hour_361,hour_362,hour_363,hour_364,hour_365,hour_366,hour_367,hour_368,hour_369,hour_370,hour_371,hour_372,hour_373,hour_374,hour_375,hour_376,hour_377,hour_378,hour_379,hour_380,hour_381,hour_382,hour_383,hour_384,hour_385,hour_386,hour_387,hour_388,hour_389,hour_390,hour_391,hour_392,hour_393,hour_394,hour_395,hour_396,hour_397,hour_398,hour_399,hour_400,hour_401,hour_402,hour_403,hour_404,hour_405,hour_406,hour_407,hour_408,hour_409,hour_410,hour_411,hour_412,hour_413,hour_414,hour_415,hour_416,hour_417,hour_418,hour_419,hour_420,hour_421,hour_422,hour_423,hour_424,hour_425,hour_426,hour_427,hour_428,hour_429,hour_430,hour_431,hour_432,hour_433,hour_434,hour_435,hour_436,hour_437,hour_438,hour_439,hour_440,hour_441,hour_442,hour_443,hour_444,hour_445,hour_446,hour_447,hour_448,hour_449,hour_450,hour_451,hour_452,hour_453,hour_454,hour_455,hour_456,hour_457,hour_458,hour_459,hour_460,hour_461,hour_462,hour_463,hour_464,hour_465,hour_466,hour_467,hour_468,hour_469,hour_470,hour_471,hour_472,hour_473,hour_474,hour_475,hour_476,hour_477,hour_478,hour_479,hour_480,hour_481,hour_482,hour_483,hour_484,hour_485,hour_486,hour_487,hour_488,hour_489,hour_490,hour_491,hour_492,hour_493,hour_494,hour_495,hour_496,hour_497,hour_498,hour_499,hour_500,hour_501,hour_502,hour_503,hour_504,hour_505,hour_506,hour_507,hour_508,hour_509,hour_510,hour_511,hour_512,hour_513,hour_514,hour_515,hour_516,hour_517,hour_518,hour_519,hour_520,hour_521,hour_522,hour_523,hour_524,hour_525,hour_526,hour_527,hour_528,hour_529,hour_530,hour_531,hour_532,hour_533,hour_534,hour_535,hour_536,hour_537,hour_538,hour_539,hour_540,hour_541,hour_542,hour_543,hour_544,hour_545,hour_546,hour_547,hour_548,hour_549,hour_550,hour_551,hour_552,hour_553,hour_554,hour_555,hour_556,hour_557,hour_558,hour_559,hour_560,hour_561,hour_562,hour_563,hour_564,hour_565,hour_566,hour_567,hour_568,hour_569,hour_570,hour_571,hour_572,hour_573,hour_574,hour_575,hour_576,hour_577,hour_578,hour_579,hour_580,hour_581,hour_582,hour_583,hour_584,hour_585,hour_586,hour_587,hour_588,hour_589,hour_590,hour_591,hour_592,hour_593,hour_594,hour_595,hour_596,hour_597,hour_598,hour_599,hour_600,hour_601,hour_602,hour_603,hour_604,hour_605,hour_606,hour_607,hour_608,hour_609,hour_610,hour_611,hour_612,hour_613,hour_614,hour_615,hour_616,hour_617,hour_618,hour_619,hour_620,hour_621,hour_622,hour_623,hour_624,hour_625,hour_626,hour_627,hour_628,hour_629,hour_630,hour_631,hour_632,hour_633,hour_634,hour_635,hour_636,hour_637,hour_638,hour_639,hour_640,hour_641,hour_642,hour_643,hour_644,hour_645,hour_646,hour_647,hour_648,hour_649,hour_650,hour_651,hour_652,hour_653,hour_654,hour_655,hour_656,hour_657,hour_658,hour_659,hour_660,hour_661,hour_662,hour_663,hour_664,hour_665,hour_666,hour_667,hour_668,hour_669,hour_670,hour_671,hour_672,hour_673,hour_674,hour_675,hour_676,hour_677,hour_678,hour_679,hour_680,hour_681,hour_682,hour_683,hour_684,hour_685,hour_686,hour_687,hour_688,hour_689,hour_690,hour_691,hour_692,hour_693,hour_694,hour_695,hour_696,hour_697,hour_698,hour_699,hour_700,hour_701,hour_702,hour_703,hour_704,hour_705,hour_706,hour_707,hour_708,hour_709,hour_710,hour_711,hour_712,hour_713,hour_714,hour_715,hour_716,hour_717,hour_718,hour_719,hour_720
0,010010201001,0.000000,0.000000,275.245902,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,514.590164,275.245902,167.540984,227.377049,0.000000,179.508197,622.295082,263.278689,167.540984,239.344262,227.377049,263.278689,0.000000,0.000000,227.377049,0.000000,191.475410,0.000000,0.000000,287.213115,275.245902,0.000000,0.000000,215.409836,0.000000,0.000000,0.000000,287.213115,478.688525,167.540984,215.409836,251.311475,0.000000,275.245902,179.508197,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,203.442623,191.475410,203.442623,0.000000,490.655738,0.000000,0.000000,203.442623,227.377049,179.508197,0.000000,0.000000,454.754098,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,167.540984,0.000000,0.000000,167.540984,0.000000,227.377049,0.000000,0.000000,0.000000,287.213115,0.000000,0.000000,0.000000,0.000000,0.000000,239.344262,0.000000,0.000000,0.000000,239.344262,167.540984,0.000000,394.918033,203.442623,0.000000,0.000000,263.278689,179.508197,0.000000,191.475410,466.721311,0.000000,502.622951,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,239.344262,0.000000,179.508197,466.721311,275.245902,0.000000,0.000000,263.278689,275.245902,251.311475,0.000000,215.409836,227.377049,167.540984,406.885246,514.590164,0.000000,0.000000,0.000000,0.000000,454.754098,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,191.475410,0.000000,0.000000,0.000000,0.000000,0.000000,502.622951,0.000000,0.000000,466.721311,741.967213,167.540984,921.475410,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,215.409836,0.000000,0.000000,0.000000,0.000000,0.000000,454.754098,239.344262,0.000000,251.311475,263.278689,251.311475,478.688525,430.819672,0.000000,179.508197,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,191.475410,0.000000,0.000000,0.000000,0.000000,0.000000,239.344262,0.000000,275.245902,287.213115,251.311475,0.000000,0.000000,227.377049,514.590164,478.688525,670.163934,179.508197,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,227.377049,0.000000,251.311475,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,251.311475,478.688525,478.688525,0.000000,287.213115,490.655738,0.000000,0.000000,0.000000,287.213115,0.000000,227.377049,0.000000,0.000000,0.000000,0.000000,0.000000,215.409836,0.000000,275.245902,0.000000,287.213115,263.278689,179.508197,179.508197,0.000000,227.377049,0.000000,406.885246,215.409836,514.590164,0.000000,0.000000,0.000000,0.000000,0.000000,227.377049,0.000000,0.00000,0.000000,0.000000,179.508197,0.000000,442.786885,287.213115,0.000000,275.245902,275.245902,0.000000,0.000000,0.000000,0.000000,694.098361,191.475410,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,466.721311,203.442623,167.540984,0.000000,0.000000,0.000000,251.311475,490.655738,682.131148,622.295082,490.655738,179.508197,394.918033,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,263.278689,718.032787,215.409836,0.000000,275.245902,275.245902,0.000000,251.311475,670.163934,0.000000,0.000000,718.032787,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,287.213115,275.245902,0.000000,0.000000,239.344262,179.508197,0.000000,502.622951,0.000000,287.213115,251.311475,454.754098,430.819672,239.344262,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,454.754098,0.000000,0.000000,394.918033,0.000000,394.918033,0.000000,287.213115,191.475410,287.213115,239.344262,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,287.213115,454.754098,263.278689,0.000000,275.245902,1089.016393,885.573770,1400.163934,849.672131,873.606557,1304.426230,885.573770,1172.786885,251.311475,418.852459,239.344262,0.000000,0.000000,191.475410,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,263.278689,0.000000,514.590164,0.000000,0.000000,0.000000,179.508197,0.000000,0.000000,0.000000,215.409836,0.000000,0.000000,191.475410,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,227.377049,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,478.688525,215.409836,0.000000,167.540984,0.000000,287.213115,179.508197,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,275.245902,0.000000,0.000000,203.442623,0.000000,0.000000,658.196721,167.540984,0.000000,0.000000,263.278689,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,227.377049,0.000000,0.000000,0.000000,167.540984,0.000000,0.000000,263.278689,0.000000,167.540984,861.639344,215.409836,0.000000,0.000000,394.918033,0.000000,0.000000,0.000000,430.819672,227.377049,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,239.344262,0.000000,0.000000,514.590164,0.000000,0.000000,0.000000,0.000000,239.344262,239.344262,490.655738,718.032787,0.000000,0.000000,0.000000,203.442623,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,167.540984,0.000000,0.000000,0.000000,0.000000,478.688525,0.000000,478.688525,227.377049,167.540984,239.344262,921.475410,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,251.311475,191.475410,454.754098,1567.704918,275.245902,1172.786885,0.000000,239.344262,0.000000,0.000000,682.131148,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,394.918033,203.442623,442.786885,215.409836,0.000000,239.344262,478.688525,0.000000,0.000000,191.475410,502.622951,251.311475,0.000000,179.508197,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,706.065574,0.000000,0.000000,0.000000,275.245902,418.852459,191.475410,0.000000,478.688525,0.000000,191.475410,203.442623,430.819672,490.655738,227.377049,275.245902,203.442623,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,418.852459,0.000000,227.377049,0.000000,287.213115,0.000000,0.000000,466.721311,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,287.213115,718.032787,634.262295,0.000000,0.000000,0.000000,203.442623,287.213115,0.000000,0.000000,706.065574,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,634.262295,0.000000,179.508197,0.000000,0.000000,0.000000,0.000000,0.000000,287.213115,179.508197,454.754098,0.000000,0.000000,0.000000,215.409836,0.000000,0.000000,502.622951,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,275.245902,0.000000,0.000000,179.508197,897.540984,215.409836,969.344262,0.000000,634.262295,514.590164,454.754098,179.508197,897.540984,670.163934,0.000000,0.000000,0.000000,0.000000

In [154]:
print("Restored actuall CBG hourly visitor (billion):")
print(restored_actual_CBG_hourly_visitor_df.iloc[:, 1:hour_cnt + 1].sum().sum()/ 1000000000)

Restored actuall CBG hourly visitor (billion):
51.028323628246746

In [155]:
restored_actual_target_hourly_visitor_df = pd.DataFrame()
restored_actual_target_hourly_visitor_df['stop'] = restored_actual_CBG_hourly_visitor_df.iloc[:, 1:hour_cnt + 1].sum(axis=0) 
print("Restored actuall target hourly visitor (billion):")
print(restored_actual_target_hourly_visitor_df['stop'].sum() / 1000000000)
restored_actual_target_hourly_visitor_df

Restored actuall target hourly visitor (billion):
51.028323628246746

                  stop
hour_1    3.619705e+07
hour_2    2.752242e+07
hour_3    2.458299e+07
hour_4    2.534076e+07
hour_5    3.077194e+07
...                ...
hour_716  9.390337e+07
hour_717  8.131823e+07
hour_718  6.743136e+07
hour_719  5.329988e+07
hour_720  3.596122e+07

[720 rows x 1 columns]

In [156]:
# save the restored actual visitor count
restored_actual_CBG_hourly_visitor_df.to_csv(restored_CBG_hourly_vistor_count_fname, index=False)
restored_actual_target_hourly_visitor_df.to_csv(restored_target_hourly_vistor_count_fname, index=False)

## IPF

### Load data

In [157]:
restored_actual_target_hourly_visitor_df = pd.read_csv(restored_target_hourly_vistor_count_fname, dtype={'CBG': str})
restored_actual_target_hourly_visitor_df

             stop
0    3.619705e+07
1    2.752242e+07
2    2.458299e+07
3    2.534076e+07
4    3.077194e+07
..            ...
715  9.390337e+07
716  8.131823e+07
717  6.743136e+07
718  5.329988e+07
719  3.596122e+07

[720 rows x 1 columns]

In [160]:
print("Restored target total visitor count (billion):")
print(restored_actual_target_hourly_visitor_df['stop'].sum() / 1000000000)

Restored target total visitor count (billion):
51.028323628246746

Load the CBG device distribution and compute the CBG aggregated restored visitors.

How to convert the CBG device distribution to stop distribution?

- option 1: convert the CBG device distribution to people distribution using device sampling rate, then using the people distribution as the stop distribution.
- option 2: compute the stop_per_device for each CBG, and then the stop for each home CBGZ, then aggregate the home CBG stops.

In [ ]:
import numpy as np
from ipfn import ipfn

restored_month_hour_outgoer_arr

aggregates = [restored_origin_arr, restored_month_hour_outgoer_arr]
dimensions = [[0], [1]]

seed_arr = np.ones((len(restored_origin_arr), len(restored_month_hour_outgoer_arr)))

IPF = ipfn.ipfn(seed_arr, aggregates, dimensions, convergence_rate=1e-3)
m = IPF.iteration()
print(m)